'use strict'

class InternetHelpers {

    /**
     * return array of string to create fake domain
     * @returns {Array<string>}
     */
    static domains() {
        return [
            'Loja do Povo',
            'Ofertas do Dia',
            ' Atacado das Ofertas ',
            'A Loja das Ofertas',
            ' Oferta do Dia',
            ' Ofertas Especiais',
            ' Ofertas de Hoje',
            ' Ofertas do Momento ',
            'Ofertas Imperdíveis Ofertas do Fim de Semana ',
            'Ofertas da Semana Ofertas do Mês ',
            'Ofertas do Ano ',
            'Ofertas do Século ',
            'Ofertas da Era ',
            'Ofertas do Milênio ',
            'Ofertas do Segundo ',
            'Milênio ',
            'Ofertas do Terceiro Milênio ',
            'Ofertas do Quarto Milênio O',
            'fertas do Quinto Milênio',
            'The Technology ',
            'Mall The Tech',
            ' Superstore ',
            'The Technology ',
            'Warehouse ',
            'The Technology ',
            'Showcase ',
            'The Tech Market T',
            'he Technology ',
            'Bazaar The Tech Emporium ',
            'The Technology Center The ',
            'Tech Stop The Technology ',
            'Place The Tech Shop',
            ' The Tech Zone The ',
            'Tech Connection ',
            'The Technology Domain The Tech Depot',
            ' The Technology Bazaar',
            ' The Tech Superstore ',
            'The Technology Zone ',
            'The Tech Connection',
            ' The Technology Corner ',
            'The Tech Network ',
            'The Technology Portal ',
            'The Tech Spot The ',
            'Technology ',
            'Page The Technology Place ',
            'The Technology Zone ',
            'The Tech Corner The',
            ' Technology Place ',
            'The Technology ',
            'Zone The Tech Connection',
            ' The Technology Domain The ',
            'Technology Center The Technology ',
            'Portal The Tech ',
            'Spot The',
            'Technology Page The Tech Zone',
            'Emagrecer com Saúde ',
            'Emagrecer com Amor',
            ' Emagrecer com Carinho',
            ' Emagrecer com Atividade Física',
            ' Emagrecer com Alegria ',
            'Emagrecer com Felicidade ',
            'Emagrecer com Satisfação ',
            'Emagrecer com Prazer',
            ' Emagrecer com Vontade ',
            'Emagrecer com Determinação',
            'Emagrecer com Força de Vontade ',
            'Emagrecer com Persistência ',
            'Casa de família',
            'Casa de laços ',
            'Casa de luz',
            'Casa de momentos ',
            'Casa de paz Casa de prazer ',
            'Casa de reflexão Casa de relax ',
            'Casa de serenidade',
            ' Casa de ternura',
            ' Casa do aconchego ',
            'Casa do bem-esta Casa do carinho',
        ]
    }

}

module.exports = InternetHelpers