'use strict'

class MarketHelpers {

    /**
     * Array of string with marker products
     * @returns {Array<string>}
     */
    static marketList() {
        return [
            "Feijão",
            "Arroz",
            "Farinha",
            "Açúcar",
            "Macarrão",
            "Biscoitos",
            "Flocos de cuscuz",
            "Óleo",
            "Azeite",
            "Extrato de tomate",
            "Molhos",
            "Vinagre",
            "Sal",
            "Café",
            "Chá",
            "Leite",
            "Maionese",
            "Mostarda",
            "Ketchup",
            "Creme de leite",
            "Leite condensado",
            "Atum",
            "Sardinha",
            "Milho de pipoca",
            "Carne moída",
            "Carne do sol",
            "Picanha",
            "Alcatra",
            "Chã de dentro",
            "Chã de fora",
            "Cupim",
            "Costela",
            "Fígado",
            "Linguiças",
            "salsichas",
            "Coxinha da asa de frango",
            "Salmão",
            "Linguado",
            "Vermelho",
            "Arraia",
            "Sardinha",
            "Robalo",
            "Pescada",
            "Merluza",
            "Camarão",
            "Polvo",
            "Hambúrguer",
            "Frango",
            "Peixe",
            "Salsicha",
            "Polpa de fruta",
            "Lasanhas",
            "Pizzas",
            "Sorvetes e açaí",
            "Batata para fritar",
            "Pão de queijo",
            "Iogurte",
            "Requeijão",
            "Queijo",
            "Presunto",
            "Mortadela",
            "Peito de peru",
            "Manteiga e margarina",
            "Massa de pastel",
            "Leite fermentado",
            "Patês",
            "Linguiça",
            "Salame",
            "Presunto",
            "Apresuntado",
            "Peito de Peru",
            "Mortadela",
            "Salsicha",
            "Bacon",
            "Carne seca",
            "Paio",
            "Refrigerantes",
            "Leite",
            "Suco de caixa",
            "Refresco",
            "Cerveja",
            "Vodka",
            "Whisky",
            "Energético",
            "Shampoo e condicionador",
            "Creme de cabelo",
            "Sabonete",
            "Creme dental",
            "Papel higiênico",
            "Lâmina de barbear",
            "Enxaguante bucal",
            "Sabão em barra",
            "Sabão em pó",
            "Amaciante",
            "Detergente de prato",
            "Água Sanitária",
            "Desinfetante",
            "Álcool",
            "Esponja",
            "Esponja de aço",
            "Lâmpadas",
            "Bateria",
            "Isqueiros",
            "Vasilhas",
            "Produtos para pet",
            "Utilidades de cozinha",
            "Artigos de decoração",
            "Eletrodomésticos",
            "Produtos de papelaria",
            "Artigos para veículos",
            "Artigos esportivos"
        ]
    }

    /**
     * Array of string with marker products
     * @returns {Array<Objec>}
     */
    static drugStore() {
        return ['NEOSORO',
            'GLIFAGE XR',
            'MAXALGINA',
            'LOSARTANA N.Q',
            'CIMEGRIPE',
            'CICLO 21',
            'PURAN T4',
            'LOSARTANA TTB',
            'CIMELIDE',
            'TORSILAX',
            'DORFLEX',
            'SILDENAFILA N.Q',
            'METFORMINA P.D',
            'LOSARTANA EMS',
            'DIPIMED',
            'SALONPAS EMPLASTRO',
            'LORATAMED',
            'HIDROCLOROTIAZIDA',
            'LOSARTANA MD7',
            'NOVALGINA',
            'ARADOIS',
            'SORIMAX',
            'BUSCOPAN CPTO',
            'LEVOTIROXINA MCK',
            'HISTAMIN',
            'SILDENAFILA EUF',
            'EXPEC',
            'STREPSILS',
            'VICK-VAPORUB',
            'MICROVLAR',
            'INFRALAX',
            'LOSARTANA P.D',
            'ATENOLOL SDZ',
            'VITER C',
            'DIPIRONA N.Q',
            'DECONGEX PLUS',
            'DIPIRONA EMS',
            'HIDROCLOROTIAZIDA MDQ',
            'IBUPRIL',
            'ENALAPRIL TTB',
            'RIVOTRIL',
            'SORO FISIOLOGICO ADV',
            'NEOSALDINA',
            'NIMESULIDA CM5',
            'TYLEMAX',
            'GLIBENCLAMIDA N.Q',
            'ATENOLOL MD7',
            'SINVASTATINA SDZ',
            'HIDROCLOROTIAZIDA TTB',
            'FLUCONAZOL CM5',
            'CEFALEXINA TTB',
            'DORALGINA',
            'DIAD',
            'BIO-C',
            'NARIDRIN',
            'SAL DE FRUTA ENO',
            'BABYMED',
            'AEROLIN',
            'CORUS',
            'DRAMIN B6',
            'HIDROCLOROTIAZIDA N.Q',
            'BEPANTRIZ',
            'ALBEL',
            'COLIRIO',
            'ENALAPRIL CM5',
            'CIFLOGEX',
            'NEODIA',
            'SIMETICONA MD7',
            'SCAFLOGIN',
            'SOMALGIN CARDIO',
            'LOSARTANA POT EUF',
            'CETOPROFENO MD7',
            'NARIX',
            'NISTA+ZINCO N.Q',
            'OMEPRAZOL TTB',
            'LACRIFILM',
            'NAPROXENO N.Q',
            'PREDSIM',
            'LOSARTANA GM2',
            'BUSONID',
            'NEOLEFRIN',
            'SODIO CLORET. ARB',
            'HIDROCLOROTIAZIDA EMS',
            'BUSCOPAN',
            'ALBENDAZOL MD7',
            'GARDENAL',
            'SELOZOK',
            'PANTOPRAZOL ACH',
            'LUFTAL',
            'TADALAFILA EUF',
            'REPOFLOR',
            'RINOSORO',
            'SINVASTATINA CM5',
            'ADVIL',
            'VONAU FLASH',
            'IVERMECTINA VMC',
            'ALIVIUM',
            'DIPIRONA GM2',
            'NEVRALGEX',
            'ENALAPRIL N.Q',
            'REXONA',
            'DOVE',
            'VALDA',
            'TRIDENT',
            'MENTOS',
            'SEMPRE LIVRE',
            'JOHNSONS BABY',
            'INTIMUS GEL',
            'NIVEA DESODORANTE',
            'NIVEA BATH',
            'SEDA',
            'MONANGE',
            'LACTA',
            'SERINGA DRK',
            'PAMPERS',
            'PROTEX',
            'RISQUE ESMALTE',
            'BAND AID',
            'BLOWTEX',
            'TURMA DA MONICA FRALDA',
            'COR E TON',
            'AGUA MINERAL CRYSTAL',
            'LUX',
            'HUGGIES',
            'NINHO FASES',
            'COMPRESSA DE GAZE CRM',
            'CAREFREE',
            'DOVE MEN CARE',
            'NIVEA BODY',
            'PRUDENCE',
            'JONTEX',
            'HUGGIES LENCOS',
            'ELSEVE',
            'COMPRESSA DE GAZE SFM',
            'PANTENE',
            'ORAL B',
            'LISTERINE',
            'COLGATE TOTAL 12',
            'HALLS',
            'ORAL B ESCOVA',
            'PRESTOBARBA',
            'ALWAYS',
            'COLGATE ESCOVA',
            'OLLA',
            'BOZZANO',
            'SERINGA DESC BEC',
            'INTIMUS',
            'COTONETES',
            'BIGFRAL',
            'CLOSE UP',
            'COCA COLA',
            'COREGA',
            'SENSODYNE',
            'AXE',
            'JOHNSONS',
            'KIT KAT',
            'NINHO LEITE',
            'CICATRISAN GAZE',
            'COLGATE',
            'KLEENEX',
            'JOHNSONS LENCOS',
            'SUAVE',
            'COMPRESSA DE GAZE AML',
            'TRESEMME',
            'NAN COMFOR',
            'NIVEA FACE',
            'K-MED',
            'SERINGA DESC. SRS',
            'CURATIVO CREMERCARE',
            'PALMOLIVE',
            'PLENITUD ACT PLUS',
            'CLEAR',
            'BEPANTOL BABY',
            'MILNUTRI',
            'NEEDS',
            'COLORAMA ESMALTE',
            'NESTOGENO',
            'KOLESTON',
            'REXONA CLINICAL',
            'FINI GELATINA',
            'REACH FIO DENTAL',
            'GILLETTE MACH 3',
            'O.B.',
            'MAXTON',
            'NEEDS SORO FISIOLOGICO',
            'PHEBO SABONETE',
            'SALON LINE',
            'COLGATE TRIPLA ACAO',
            'GRAVTEST',
            'ENTEROGERMINA',
            'ESPARADRAPO CMR',
            'OFF',
            'BEPANTOL DERMA',
            'SNICKERS',
            'GRANADO BEBE SABONTE LIQUIDO',
            'DOVE BABY',
            'BATON',
            'SOFTYS',
            'ANTHELIOS',
            'ASEPXIA',
        ]
    }


    /**
    * Array of string with eletro products
    * @returns {Array<Objec>}
    */
    static eletro() {
        return [
            'ASPIRADOR DE PÓ',
            'FERRO (TRADICIONAL)',
            'MÁQUINA DE LAVAR ROUPA',
            'BEBEDOURO',
            'MIXER',
            'ESPREMEDOR DE FRUTAS',
            'LIQUIDIFICADOR',
            'BATEDEIRA',
            'SANDUICHEIRA',
            'TORRADEIRA',
            'FORNINHO ELÉTRICO',
            'MÁQUINA DE LAVAR LOUÇAS',
            'GELADEIRA (COM FREEZER)',
            'FOGÃO',
            'COIFA',
            'VENTILADOR ',
            'CAFETEIRA',
            'TELEFONE',
            'ASPIRADOR DE PÓ PORTÁTIL',
            'FERRO Á VAPOR VERTICAL',
            'ADEGA CLIMATIZADA',
        ]
    }

    /**
    * Array of string with marker products
    * @returns {Array<Objec>}
    */
    static pcMarket() {
        return ['Adaptador',
            'Cabo',
            'Caixa de som',
            'Cartucho Compátivel',
            'Cartucho Canon',
            'Cartucho Epson',
            'Cartucho HP',
            'Cartucho Lexmark',
            'Estabilizador',
            'Etiqueta Ink jet',
            'Etiqueta matricial',
            'Filtro de linha',
            'Fita dat',
            'Fita para impressora',
            'Fita para PDV',
            'Fone de ouvido',
            'Formulário contínuo',
            'Fonte',
            'Joystick',
            'Mouse',
            'Mouse pad',
            'MP3',
            'MP4',
            'No-break',
            'Papel para Ink Jet /Laser',
            'Papel fotográfico',
            'Papel para ploter',
            'Pasta para formulário contínuo',
            'Pen drive',
            'Porta cd',
            'Porta CPU',
            'Protetor de tela',
            'Teclado',
            'Toner HP',
            'Toner Lexmark',
            'Transparências',
            'Web cam',
            'Monitor',
            'Fonte',
            'Cabo USB',
            'Memoria RAM',
            'SSD',
            'Gabinete',
            'CPU'
        ]
    }

    /**
    * return array o array with string
    * @returns {Array<array>}
    */
    static pc() {
        return [
            [
                'Intel Core i5-10210U (10ª geração);',
                'SSD de 512GB;',
                '8GB de memória RAM;',
                'Tela de 15.6" com resolução HD;',
                'Windows 10;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Intel Core i3 1115G4 (11ª geração);',
                '4GB memória RAM DDR4;',
                'SSD de 256GB de armazenamento;',
                'Tela LED HD de 15.6";',
                'Windows 10;',
                'Duas portas USB 3.1 Gen 1 e uma porta USB 2.0;',
                'HDMI.',
            ],
            [
                'Intel Core i7-10510U (10ª geração);',
                '8GB de memória RAM;',
                'Placa de vídeo dedicada NVIDIA GeForce MX110 de 2GB;',
                'HDD de 1TB;',
                'SSD de 128GB;',
                'Tela LED de 15.6" HD antirreflexo;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'Windows 10;',
                'HDMI.',
            ],
            [
                'Intel i5-10210U (10ª geração);',
                '8GB de memória RAM DDR4;',
                '1TB de HDD;',
                'Tela LCD Full HD de 15.6" antirreflexo;',
                'Uma porta USB 2.0 e três portas USB 3.0;',
                'Windows 10;',
                'HDMI.',
            ],
            [
                'Intel i7 1165G7 (11ª geração);',
                '8GB de memória RAM DDR4;',
                'SSD de 256GB;',
                'Tela antireflexo Full HD de 15.6";',
                'Windows 10;',
                'Duas portas USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Celeron;',
                '4GB de memória RAM;',
                'SSD de 64GB;',
                'Tela Full HD 13.3";',
                'Windows 10;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Core i5-10210U (10ª geração);',
                '8GB de memória RAM DDR4;',
                'HDD de 1TB;',
                'Windows 10;',
                'Tela de 15.6" NanoEdge;',
                'Duas portas USB 2.0;',
                'HDMI.',
            ],
            [
            'Intel i7 11800H (11ª geração);',
            'NVIDIA GeForce RTX 3060 6GB GDDR6;',
            'SSD de 512GB;',
            '16GB de memória RAM DDR4;',
            'Tela de 15.6" Full HD;',
            'Duas portas USB 2.0 e uma porta USB 3.0;',
            'Windows 10;',
            'HDMI.',
            ]
        ]
    }

    /**
    * Array of string with marker products
    * @returns {Array<string>}
    */
    static clothes(){
        return [
            'Camiseta',
            'Camisa',
            'Camisa gola polo',
            'Camisola',
            'Camisa de manga comprida',
            'Camisa de manga curta',
            'Jaqueta',
            'Jaqueta jeans',
            'Croped',
            'Baby look',
            'Casaco',
            'Casaco moletom',
            'Cueca',
            'Calcinha',
            'Cueca box',
            'Bermuda',
            'Short',
            'Calça',
            'Calça jeans',
            'Meia',
            'Boné',
            'Gorro',
            'Boina',
            'Saia',
            'Sutiã',
            'Tomara-que-caia'
        ]
    }

}

module.exports = MarketHelpers