'use strict'

class MarketHelpers {

    /**
     * Array of string with marker products
     * @returns {Array<string>}
     */
    static marketList() {
        return [
            "Feijão",
            "Arroz",
            "Farinha",
            "Açúcar",
            "Macarrão",
            "Biscoitos",
            "Flocos de cuscuz",
            "Óleo",
            "Azeite",
            "Extrato de tomate",
            "Molhos",
            "Vinagre",
            "Sal",
            "Café",
            "Chá",
            "Leite",
            "Maionese",
            "Mostarda",
            "Ketchup",
            "Creme de leite",
            "Leite condensado",
            "Atum",
            "Sardinha",
            "Milho de pipoca",
            "Carne moída",
            "Carne do sol",
            "Picanha",
            "Alcatra",
            "Chã de dentro",
            "Chã de fora",
            "Cupim",
            "Costela",
            "Fígado",
            "Linguiças",
            "salsichas",
            "Coxinha da asa de frango",
            "Salmão",
            "Linguado",
            "Vermelho",
            "Arraia",
            "Sardinha",
            "Robalo",
            "Pescada",
            "Merluza",
            "Camarão",
            "Polvo",
            "Hambúrguer",
            "Frango",
            "Peixe",
            "Salsicha",
            "Polpa de fruta",
            "Lasanhas",
            "Pizzas",
            "Sorvetes e açaí",
            "Batata para fritar",
            "Pão de queijo",
            "Iogurte",
            "Requeijão",
            "Queijo",
            "Presunto",
            "Mortadela",
            "Peito de peru",
            "Manteiga e margarina",
            "Massa de pastel",
            "Leite fermentado",
            "Patês",
            "Linguiça",
            "Salame",
            "Presunto",
            "Apresuntado",
            "Peito de Peru",
            "Mortadela",
            "Salsicha",
            "Bacon",
            "Carne seca",
            "Paio",
            "Refrigerantes",
            "Leite",
            "Suco de caixa",
            "Refresco",
            "Cerveja",
            "Vodka",
            "Whisky",
            "Energético",
            "Shampoo e condicionador",
            "Creme de cabelo",
            "Sabonete",
            "Creme dental",
            "Papel higiênico",
            "Lâmina de barbear",
            "Enxaguante bucal",
            "Sabão em barra",
            "Sabão em pó",
            "Amaciante",
            "Detergente de prato",
            "Água Sanitária",
            "Desinfetante",
            "Álcool",
            "Esponja",
            "Esponja de aço",
            "Lâmpadas",
            "Bateria",
            "Isqueiros",
            "Vasilhas",
            "Produtos para pet",
            "Utilidades de cozinha",
            "Artigos de decoração",
            "Eletrodomésticos",
            "Produtos de papelaria",
            "Artigos para veículos",
            "Artigos esportivos"
        ]
    }

    /**
     * Array of string with marker products
     * @returns {Array<Objec>}
     */
    static drugStore() {
        return ['NEOSORO',
            'GLIFAGE XR',
            'MAXALGINA',
            'LOSARTANA N.Q',
            'CIMEGRIPE',
            'CICLO 21',
            'PURAN T4',
            'LOSARTANA TTB',
            'CIMELIDE',
            'TORSILAX',
            'DORFLEX',
            'SILDENAFILA N.Q',
            'METFORMINA P.D',
            'LOSARTANA EMS',
            'DIPIMED',
            'SALONPAS EMPLASTRO',
            'LORATAMED',
            'HIDROCLOROTIAZIDA',
            'LOSARTANA MD7',
            'NOVALGINA',
            'ARADOIS',
            'SORIMAX',
            'BUSCOPAN CPTO',
            'LEVOTIROXINA MCK',
            'HISTAMIN',
            'SILDENAFILA EUF',
            'EXPEC',
            'STREPSILS',
            'VICK-VAPORUB',
            'MICROVLAR',
            'INFRALAX',
            'LOSARTANA P.D',
            'ATENOLOL SDZ',
            'VITER C',
            'DIPIRONA N.Q',
            'DECONGEX PLUS',
            'DIPIRONA EMS',
            'HIDROCLOROTIAZIDA MDQ',
            'IBUPRIL',
            'ENALAPRIL TTB',
            'RIVOTRIL',
            'SORO FISIOLOGICO ADV',
            'NEOSALDINA',
            'NIMESULIDA CM5',
            'TYLEMAX',
            'GLIBENCLAMIDA N.Q',
            'ATENOLOL MD7',
            'SINVASTATINA SDZ',
            'HIDROCLOROTIAZIDA TTB',
            'FLUCONAZOL CM5',
            'CEFALEXINA TTB',
            'DORALGINA',
            'DIAD',
            'BIO-C',
            'NARIDRIN',
            'SAL DE FRUTA ENO',
            'BABYMED',
            'AEROLIN',
            'CORUS',
            'DRAMIN B6',
            'HIDROCLOROTIAZIDA N.Q',
            'BEPANTRIZ',
            'ALBEL',
            'COLIRIO',
            'ENALAPRIL CM5',
            'CIFLOGEX',
            'NEODIA',
            'SIMETICONA MD7',
            'SCAFLOGIN',
            'SOMALGIN CARDIO',
            'LOSARTANA POT EUF',
            'CETOPROFENO MD7',
            'NARIX',
            'NISTA+ZINCO N.Q',
            'OMEPRAZOL TTB',
            'LACRIFILM',
            'NAPROXENO N.Q',
            'PREDSIM',
            'LOSARTANA GM2',
            'BUSONID',
            'NEOLEFRIN',
            'SODIO CLORET. ARB',
            'HIDROCLOROTIAZIDA EMS',
            'BUSCOPAN',
            'ALBENDAZOL MD7',
            'GARDENAL',
            'SELOZOK',
            'PANTOPRAZOL ACH',
            'LUFTAL',
            'TADALAFILA EUF',
            'REPOFLOR',
            'RINOSORO',
            'SINVASTATINA CM5',
            'ADVIL',
            'VONAU FLASH',
            'IVERMECTINA VMC',
            'ALIVIUM',
            'DIPIRONA GM2',
            'NEVRALGEX',
            'ENALAPRIL N.Q',
            'REXONA',
            'DOVE',
            'VALDA',
            'TRIDENT',
            'MENTOS',
            'SEMPRE LIVRE',
            'JOHNSONS BABY',
            'INTIMUS GEL',
            'NIVEA DESODORANTE',
            'NIVEA BATH',
            'SEDA',
            'MONANGE',
            'LACTA',
            'SERINGA DRK',
            'PAMPERS',
            'PROTEX',
            'RISQUE ESMALTE',
            'BAND AID',
            'BLOWTEX',
            'TURMA DA MONICA FRALDA',
            'COR E TON',
            'AGUA MINERAL CRYSTAL',
            'LUX',
            'HUGGIES',
            'NINHO FASES',
            'COMPRESSA DE GAZE CRM',
            'CAREFREE',
            'DOVE MEN CARE',
            'NIVEA BODY',
            'PRUDENCE',
            'JONTEX',
            'HUGGIES LENCOS',
            'ELSEVE',
            'COMPRESSA DE GAZE SFM',
            'PANTENE',
            'ORAL B',
            'LISTERINE',
            'COLGATE TOTAL 12',
            'HALLS',
            'ORAL B ESCOVA',
            'PRESTOBARBA',
            'ALWAYS',
            'COLGATE ESCOVA',
            'OLLA',
            'BOZZANO',
            'SERINGA DESC BEC',
            'INTIMUS',
            'COTONETES',
            'BIGFRAL',
            'CLOSE UP',
            'COCA COLA',
            'COREGA',
            'SENSODYNE',
            'AXE',
            'JOHNSONS',
            'KIT KAT',
            'NINHO LEITE',
            'CICATRISAN GAZE',
            'COLGATE',
            'KLEENEX',
            'JOHNSONS LENCOS',
            'SUAVE',
            'COMPRESSA DE GAZE AML',
            'TRESEMME',
            'NAN COMFOR',
            'NIVEA FACE',
            'K-MED',
            'SERINGA DESC. SRS',
            'CURATIVO CREMERCARE',
            'PALMOLIVE',
            'PLENITUD ACT PLUS',
            'CLEAR',
            'BEPANTOL BABY',
            'MILNUTRI',
            'NEEDS',
            'COLORAMA ESMALTE',
            'NESTOGENO',
            'KOLESTON',
            'REXONA CLINICAL',
            'FINI GELATINA',
            'REACH FIO DENTAL',
            'GILLETTE MACH 3',
            'O.B.',
            'MAXTON',
            'NEEDS SORO FISIOLOGICO',
            'PHEBO SABONETE',
            'SALON LINE',
            'COLGATE TRIPLA ACAO',
            'GRAVTEST',
            'ENTEROGERMINA',
            'ESPARADRAPO CMR',
            'OFF',
            'BEPANTOL DERMA',
            'SNICKERS',
            'GRANADO BEBE SABONTE LIQUIDO',
            'DOVE BABY',
            'BATON',
            'SOFTYS',
            'ANTHELIOS',
            'ASEPXIA',
        ]
    }

    
    /**
    * Array of string with eletro products
    * @returns {Array<Objec>}
    */
    static eletro() {
        return [
            'ASPIRADOR DE PÓ',
            'FERRO (TRADICIONAL)',
            'MÁQUINA DE LAVAR ROUPA',
            'BEBEDOURO',
            'MIXER',
            'ESPREMEDOR DE FRUTAS',
            'LIQUIDIFICADOR',
            'BATEDEIRA',
            'SANDUICHEIRA',
            'TORRADEIRA',
            'FORNINHO ELÉTRICO',
            'MÁQUINA DE LAVAR LOUÇAS',
            'GELADEIRA (COM FREEZER)',
            'FOGÃO',
            'COIFA',
            'VENTILADOR ',
            'CAFETEIRA',
            'TELEFONE',
            'ASPIRADOR DE PÓ PORTÁTIL',
            'FERRO Á VAPOR VERTICAL',
            'ADEGA CLIMATIZADA',
        ]
    }
}

module.exports = MarketHelpers