'use strict'

class MarketHelpers {

    /**
    * Array of string with marker products
    * @returns {Array<string>}
    */
    static cellPhone() {
        return [
            "iPhone",
            "iPhone 13 Pro Max",
            "iPhone 14 Pro Max",
            "Samsung Galaxy A13",
            "iPhone 13 Pro",
            "iPhone 12",
            "iPhone 14",
            "iPhone 14 Pro",
            "iPhone SE 2022",
            "Samsung Galaxy A03",
            "iPhone 11 Branco, ",
            "Galaxy A03 Core Preto,",
            "iPhone 13 Preto, ",
            "iPhone 11 Preto, ",
            "Galaxy A32 Branco, ",
            "Galaxy S20 FE 5G Azul-Marinho, ",
            "iPhone 13 Rosa, ",
            "Galaxy A53 5G Preto, ",
            "iPhone 11 Branco,",
            "iPhone XR ",
            "Samsung Galaxy J4 Core",
            "Samsung Galaxy J5 Prime ",
            "iPhone 7 ",
            "iPhone 8 ",
            "Motorola Moto G6 Play ",
            "Samsung Galaxy J7 Prime ",
            "iPhone 8 Plus ",
            "Samsung Galaxy A30s ",
            "Samsung Galaxy A10 ",
            "iPhone 11",
            "iPhone 7 ",
            "iPhone XR",
            "iPhone 8 Plus",
            "iPhone X",
            "iPhone 8 ",
            "iPhone 7 Plus",
            "iPhone 6s ",
            "Galaxy A10 ",
            "iPhone 12",
            "Samsung",
            "Motorola",
            "Apple",
            "Xiaomi",
            "LG",
            "Asus"
        ]
    }

    /**
    * Array of string with marker products
    * @returns {Array<string>}
    */
    static construction() {
        return [
            "Adaptador soldável curto 25mm x 3 / 4",
            "Anel de vedação 100mm",
            "Argamassa AC1",
            "Armação 1 Estribo",
            "Arruela 3 / 4",
            "Assento simples p / sanitário",
            "Bacia Sanitária simples",
            "Bico p / engate rápido 1 / 2",
            "Bocal E - 27 c / rabicho",
            "Brita nº3",
            "Brita nº4",
            "Broxa p / pintura",
            "Bucha p / tubo 3 / 4",
            "Cabo Flexível 2, 5mm2",
            "Cabo Flexível 4mm2",
            "Cabo p / Entrada de energia",
            "Caixa de Inspeção PVC",
            "Caixa de Ligação provisória",
            "Caixa de Medição Monofásica",
            "Caixa descarga simples",
            "Carga de macadame",
            "Cinta de Alumínio",
            "Conector cunha",
            "Conector p / Haste",
            "Conexão simples para torneira",
            "Curva esgoto 90º 100mm",
            "Disjuntor monofásico 40A",
            "Dobradiça simples",
            "Eletroduto 3 / 4",
            "Engate flexível 40 cm p / Bacil",
            "Engate rápido 1 / 2",
            "Entrega",
            "Espude para vaso",
            "Filtro de concreto p / Esgoto",
            "Fio Rígido 10mm",
            "Fita Isolante",
            "Fita Veda Rosca",
            "Fossa de concreto",
            "Haste de Terra cobreada comum",
            "Interruptor 1TS Externo",
            "Joelho Esgoto 90º 100mm",
            "Joelho Soldável 90º 20mm x 1 / 2",
            "Joelho Soldável c / bucha latão 90º 25mm x 1 / 2",
            "Lona plastica preta",
            "Luva esgoto 100mm",
            "Maderit 1, 10 x 2, 20",
            "Mangueira de Jardim",
            "Manta Asfática 3mm",
            "Manta de bidim p / Drenagem 2, 30m largura",
            "Manta de bidim p / Drenagem mcdrain",
            "Parafuso Máquina",
            "Pino macho bipolar 10A",
            "Prego c / cabeça 16×24",
            "Prego telheiro",
            "Silicone",
            "Suporte p / Caixa de Medição",
            "TE esgoto 100mm",
            "TE soldável 25mm",
            "Telha Ondulada fibrocimento 4mm 2, 44m x 0, 50m",
            "Tomada barra",
            "Tomada Nylon",
            "Torneira Plastica de Jardim 1 / 2",
            "Tubo descarga p / caixa",
            "Tubo Drenagem",
            "Tubo esgoto 100mm",
            "Tubo soldável 25mm",
            "Arame Recozido 10",
            "Arame Recozido 18",
            "Areia c / Brita 0",
            "Areia c / Brita 1",
            "Areia Média",
            "Cimento",
            "Concreto Usinado",
            "Escoras 3m",
            "Lage até 4m",
            "Lage até 5, 3m",
            "Manta Asfática 3mm",
            "Prego 17×27",
            "Tabuas largura variada 2, 5cm larg.Pinus",
            "Tinta asfáltica p / Concreto",
            "Vedacit",
            "Vergalhão 10mm",
            "Vergalhão 5mm",
            "Vergalhão 8mm",
            "Adesivo p / Chapisco",
            "Arame Recozido 10",
            "Arame Recozido 18",
            "Areia c / Brita 0",
            "Areia Média",
            "Argamassa AC2",
            "Caixa de Luz 2×4",
            "Caixa de Luz 4×4",
            "Caixa de Luz de Teto – Concreto",
            "Canaflex 1.1 / 2",
            "Cimento",
            "Espaceador p / vergalhão 25m",
            "Graute",
            "Lage até 4m",
            "Mangueira Corrugada 3 / 4",
            "Mangueira Corrugada 3 / 4 reforçada",
            "Prego 17×27",
            "Prego cab dupla 17×27",
            "Quadro de distribuição 12 / 16 disj",
            "Quadro de distribuição 18 / 24 disj",
            "Tabuas largura variada 2, 5cm larg.Pinus",
            "Tijolos 6 furos 9X14X29",
            "Tubo PVC 300mm",
            "Vergalhão 10mm",
            "Vergalhão 12, 5mm",
            "Vergalhão 5mm",
            "Vergalhão 6, 3mm",
            "Vergalhão 8mm",
            "Arame Recozido 10",
            "Arame Recozido 18",
            "Areia c / Brita 0",
            "Caixa de Luz 2×4",
            "Cimento",
            "Escoras 6m",
            "Expansor de cimento",
            "Lage acima 4m",
            "Lage até 4m",
            "Lona plastica preta",
            "Madeira da Caixa d’ água",
            "Parafuso telheiro",
            "Pincel 2",
            "Prego 17×27",
            "Prego cab dupla 17×27",
            "Rufos / Pigadeira",
            "Silicone",
            "Tabuas largura variada 2, 5cm larg.Pinus",
            "Taxa",
            "Telha Ondulada fibra incolor 1mm 2, 44m x 1, 10m",
            "Telha Ondulada fibrocimento 6mm 1, 83m x 1, 10m",
            "Telha Portuguesa – Meia Telha",
            "Telha Portuguesa reforçada",
            "Telha Portuguesa reforçada – Cumeeira",
            "Telha Portuguesa reforçada – Terminal",
            "Tinta Impermeabilizante p / telhas",
            "Vergalhão 10mm",
            "Vergalhão 5mm",
            "Vergalhão 8mm",
            "Adaptador flange 25mm x 3 / 4",
            "Adaptador soldável ajustável caixa d’água 25mm x 3 / 4",
            "Adaptador soldável ajustável caixa d’água 32mm x 1",
            "Adaptador soldável curto 25mm x 3 / 4",
            "Adaptador soldável curto 50mm x 1.1 / 2",
            "Adaptador transição F / F PPR 25mm x 3 / 4",
            "Adaptador transição F / M PPR 32mm x 1",
            "Anel de vedação 100mm",
            "Anel de vedação 50mm",
            "Anel de vedação 75mm",
            "Arame Galvanizado",
            "Broca videa 5mm",
            "Bucha de redução esgoto 50mm x 40mm",
            "Bucha de redução MF PPR 32mm x 25mm",
            "Bucha de redução soldável curta 25mm x 20mm",
            "Bucha de redução soldável curta 32mm x 25mm",
            "Bucha de redução soldável longa 40mm x 25mm",
            "Bucha de redução soldável longa 50mm x 25mm",
            "Bucha nylon 10mm",
            "Caixa da Água 1000l",
            "Caixa da Água 2000l",
            "Caixa da Água 500l",
            "Caixa de Gordura de Concreto",
            "Caixa sifonada",
            "Cap esgoto 100mm",
            "Cap PPR 25mm",
            "Cap Soldável 25mm",
            "Cap Soldável 32mm",
            "Cola p / Tubo Soldavel 175g c / pincel",
            "Cola p / Tubo Soldavel 73g",
            "Curva esgoto 90º 100mm",
            "Curva esgoto 90º 40mm",
            "Curva esgoto 90º 50mm",
            "Curva esgoto 90º 75mm",
            "Curva esgoto curta 90º 100mm",
            "Curva esgoto curta 90º 50mm",
            "Curva soldável 90º 25mm",
            "Curva soldável 90º 32mm",
            "Curva soldável 90º 50mm",
            "Curva transposição Soldave, 25mm",
            "Fita Crepe",
            "Fita Veda Rosca",
            "Fita zincada",
            "Grelha quadrada 100mm p / Ralo Inóx",
            "Joelho Esgoto 45º 100mm",
            "Joelho Esgoto 45º 40mm",
            "Joelho Esgoto 45º 50mm",
            "Joelho Esgoto 45º 75mm",
            "Joelho Esgoto 90º 100mm",
            "Joelho Esgoto 90º 32mm",
            "Joelho Esgoto 90º 40mm",
            "Joelho Esgoto 90º 50mm",
            "Joelho Esgoto 90º 75mm",
            "Joelho esgoto c / anel labial 90º 40mm",
            "Joelho Misto PPR F / F 90º 32mm x 1 / 2",
            "Joelho PPR 45º 25mm",
            "Joelho PPR 45º 32mm",
            "Joelho PPR F / F 45º 25mm",
            "Joelho PPR F / F 90º 25mm",
            "Joelho PPR F / F 90º 25mm x 1 / 2",
            "Joelho PPR F / F 90º 32mm",
            "Joelho PPR F / F 90º 32mm x 3 / 4",
            "Joelho Soldável 45º 25mm",
            "Joelho Soldável 45º 32mm",
            "Joelho Soldável 45º 50mm",
            "Joelho Soldável 90º 25mm",
            "Joelho Soldável 90º 25mm x 3 / 4",
            "Joelho Soldável 90º 32mm",
            "Joelho Soldável c / bucha latão 90º 25mm x 1 / 2",
            "Junção esgoto 45º 50mm",
            "Lixa d’água grão 80",
            "Lixa ferro grão 100",
            "Lixa ferro grão 120",
            "Lixa ferro grão 80",
            "Luva esgoto 100mm",
            "Luva esgoto 40mm",
            "Luva esgoto 50mm",
            "Luva esgoto 75mm",
            "Luva PPR F / F 25mm",
            "Luva PPR F / F 32mm",
            "Luva PPR F / F 32mm x 25mm",
            "Luva soldável 25mm",
            "Luva soldável 32mm",
            "Luva soldável 50mm",
            "Luva soldável azul 32mm x 1",
            "Mangueira de nível",
            "Manta Lã de vidro 20Kg / m3 1220 X 15300 X 50mm",
            "Marreta 1Kg",
            "Pá",
            "Pasta Lubrificante 160g",
            "Pasta Lubrificante 175g",
            "Pasta Lubrificante 80g",
            "Plug Roscavel 1 / 2",
            "Plug Roscavel 3 / 4",
            "Registro de pressão 3 / 4",
            "Registro Esfera soldável 25mm",
            "Registro Esfera soldável 32mm",
            "Registro Esfera soldável 50mm",
            "Registro Gaveta 1",
            "Registro Gaveta 3 / 4",
            "Registro Gaveta Bruto volante 3 / 4",
            "TE esgoto 100mm",
            "TE esgoto 100mm x 50mm",
            "TE esgoto 100mm x 75mm",
            "TE esgoto 40mm",
            "TE esgoto 50mm",
            "TE esgoto 90º 100mm x 50mm",
            "TE F / F PPR 25mm",
            "TE F / F PPR 32mm",
            "TE F / F PPR 32mm x 25mm",
            "TE misturador PPR 25 x 3 / 4",
            "TE soldável 25mm",
            "TE soldável 32mm",
            "TE soldável 32mm x 25mm",
            "TE soldável 50mm",
            "Torneira Bóia",
            "Tubo de Cobre 1 / 2",
            "Tubo esgoto 100mm",
            "Tubo esgoto 40mm",
            "Tubo esgoto 50mm",
            "Tubo esgoto 75mm",
            "Tubo PPR 25mm",
            "Tubo PPR 32mm",
            "Tubo soldável 25mm",
            "Tubo soldável 32mm",
            "Vassoura",
            "Adesivo p / Chapisco",
            "Areia de Reboco",
            "Areia Média",
            "Argamassa AC2",
            "Cal Hidratada",
            "Cal Líquido",
            "Cimento",
            "Prego 17×27",
            "Prego 19×36",
            "Sela Infiltrações 18kg cinza",
            "Tela p / Reboco",
            "Vedacit",

        ]
    }

    /**
     * Array of string with marker products
     * @returns {Array<string>}
     */
    static marketList() {
        return [
            "Feijão",
            "Arroz",
            "Farinha",
            "Açúcar",
            "Macarrão",
            "Biscoitos",
            "Flocos de cuscuz",
            "Óleo",
            "Azeite",
            "Extrato de tomate",
            "Molhos",
            "Vinagre",
            "Sal",
            "Café",
            "Chá",
            "Leite",
            "Maionese",
            "Mostarda",
            "Ketchup",
            "Creme de leite",
            "Leite condensado",
            "Atum",
            "Sardinha",
            "Milho de pipoca",
            "Carne moída",
            "Carne do sol",
            "Picanha",
            "Alcatra",
            "Chã de dentro",
            "Chã de fora",
            "Cupim",
            "Costela",
            "Fígado",
            "Linguiças",
            "salsichas",
            "Coxinha da asa de frango",
            "Salmão",
            "Linguado",
            "Vermelho",
            "Arraia",
            "Sardinha",
            "Robalo",
            "Pescada",
            "Merluza",
            "Camarão",
            "Polvo",
            "Hambúrguer",
            "Frango",
            "Peixe",
            "Salsicha",
            "Polpa de fruta",
            "Lasanhas",
            "Pizzas",
            "Sorvetes e açaí",
            "Batata para fritar",
            "Pão de queijo",
            "Iogurte",
            "Requeijão",
            "Queijo",
            "Presunto",
            "Mortadela",
            "Peito de peru",
            "Manteiga e margarina",
            "Massa de pastel",
            "Leite fermentado",
            "Patês",
            "Linguiça",
            "Salame",
            "Presunto",
            "Apresuntado",
            "Peito de Peru",
            "Mortadela",
            "Salsicha",
            "Bacon",
            "Carne seca",
            "Paio",
            "Refrigerantes",
            "Leite",
            "Suco de caixa",
            "Refresco",
            "Cerveja",
            "Vodka",
            "Whisky",
            "Energético",
            "Shampoo e condicionador",
            "Creme de cabelo",
            "Sabonete",
            "Creme dental",
            "Papel higiênico",
            "Lâmina de barbear",
            "Enxaguante bucal",
            "Sabão em barra",
            "Sabão em pó",
            "Amaciante",
            "Detergente de prato",
            "Água Sanitária",
            "Desinfetante",
            "Álcool",
            "Esponja",
            "Esponja de aço",
            "Lâmpadas",
            "Bateria",
            "Isqueiros",
            "Vasilhas",
            "Produtos para pet",
            "Utilidades de cozinha",
            "Artigos de decoração",
            "Eletrodomésticos",
            "Produtos de papelaria",
            "Artigos para veículos",
            "Artigos esportivos"
        ]
    }

    /**
     * Array of string with marker products
     * @returns {Array<Objec>}
     */
    static drugStore() {
        return ['NEOSORO',
            'GLIFAGE XR',
            'MAXALGINA',
            'LOSARTANA N.Q',
            'CIMEGRIPE',
            'CICLO 21',
            'PURAN T4',
            'LOSARTANA TTB',
            'CIMELIDE',
            'TORSILAX',
            'DORFLEX',
            'SILDENAFILA N.Q',
            'METFORMINA P.D',
            'LOSARTANA EMS',
            'DIPIMED',
            'SALONPAS EMPLASTRO',
            'LORATAMED',
            'HIDROCLOROTIAZIDA',
            'LOSARTANA MD7',
            'NOVALGINA',
            'ARADOIS',
            'SORIMAX',
            'BUSCOPAN CPTO',
            'LEVOTIROXINA MCK',
            'HISTAMIN',
            'SILDENAFILA EUF',
            'EXPEC',
            'STREPSILS',
            'VICK-VAPORUB',
            'MICROVLAR',
            'INFRALAX',
            'LOSARTANA P.D',
            'ATENOLOL SDZ',
            'VITER C',
            'DIPIRONA N.Q',
            'DECONGEX PLUS',
            'DIPIRONA EMS',
            'HIDROCLOROTIAZIDA MDQ',
            'IBUPRIL',
            'ENALAPRIL TTB',
            'RIVOTRIL',
            'SORO FISIOLOGICO ADV',
            'NEOSALDINA',
            'NIMESULIDA CM5',
            'TYLEMAX',
            'GLIBENCLAMIDA N.Q',
            'ATENOLOL MD7',
            'SINVASTATINA SDZ',
            'HIDROCLOROTIAZIDA TTB',
            'FLUCONAZOL CM5',
            'CEFALEXINA TTB',
            'DORALGINA',
            'DIAD',
            'BIO-C',
            'NARIDRIN',
            'SAL DE FRUTA ENO',
            'BABYMED',
            'AEROLIN',
            'CORUS',
            'DRAMIN B6',
            'HIDROCLOROTIAZIDA N.Q',
            'BEPANTRIZ',
            'ALBEL',
            'COLIRIO',
            'ENALAPRIL CM5',
            'CIFLOGEX',
            'NEODIA',
            'SIMETICONA MD7',
            'SCAFLOGIN',
            'SOMALGIN CARDIO',
            'LOSARTANA POT EUF',
            'CETOPROFENO MD7',
            'NARIX',
            'NISTA+ZINCO N.Q',
            'OMEPRAZOL TTB',
            'LACRIFILM',
            'NAPROXENO N.Q',
            'PREDSIM',
            'LOSARTANA GM2',
            'BUSONID',
            'NEOLEFRIN',
            'SODIO CLORET. ARB',
            'HIDROCLOROTIAZIDA EMS',
            'BUSCOPAN',
            'ALBENDAZOL MD7',
            'GARDENAL',
            'SELOZOK',
            'PANTOPRAZOL ACH',
            'LUFTAL',
            'TADALAFILA EUF',
            'REPOFLOR',
            'RINOSORO',
            'SINVASTATINA CM5',
            'ADVIL',
            'VONAU FLASH',
            'IVERMECTINA VMC',
            'ALIVIUM',
            'DIPIRONA GM2',
            'NEVRALGEX',
            'ENALAPRIL N.Q',
            'REXONA',
            'DOVE',
            'VALDA',
            'TRIDENT',
            'MENTOS',
            'SEMPRE LIVRE',
            'JOHNSONS BABY',
            'INTIMUS GEL',
            'NIVEA DESODORANTE',
            'NIVEA BATH',
            'SEDA',
            'MONANGE',
            'LACTA',
            'SERINGA DRK',
            'PAMPERS',
            'PROTEX',
            'RISQUE ESMALTE',
            'BAND AID',
            'BLOWTEX',
            'TURMA DA MONICA FRALDA',
            'COR E TON',
            'AGUA MINERAL CRYSTAL',
            'LUX',
            'HUGGIES',
            'NINHO FASES',
            'COMPRESSA DE GAZE CRM',
            'CAREFREE',
            'DOVE MEN CARE',
            'NIVEA BODY',
            'PRUDENCE',
            'JONTEX',
            'HUGGIES LENCOS',
            'ELSEVE',
            'COMPRESSA DE GAZE SFM',
            'PANTENE',
            'ORAL B',
            'LISTERINE',
            'COLGATE TOTAL 12',
            'HALLS',
            'ORAL B ESCOVA',
            'PRESTOBARBA',
            'ALWAYS',
            'COLGATE ESCOVA',
            'OLLA',
            'BOZZANO',
            'SERINGA DESC BEC',
            'INTIMUS',
            'COTONETES',
            'BIGFRAL',
            'CLOSE UP',
            'COCA COLA',
            'COREGA',
            'SENSODYNE',
            'AXE',
            'JOHNSONS',
            'KIT KAT',
            'NINHO LEITE',
            'CICATRISAN GAZE',
            'COLGATE',
            'KLEENEX',
            'JOHNSONS LENCOS',
            'SUAVE',
            'COMPRESSA DE GAZE AML',
            'TRESEMME',
            'NAN COMFOR',
            'NIVEA FACE',
            'K-MED',
            'SERINGA DESC. SRS',
            'CURATIVO CREMERCARE',
            'PALMOLIVE',
            'PLENITUD ACT PLUS',
            'CLEAR',
            'BEPANTOL BABY',
            'MILNUTRI',
            'NEEDS',
            'COLORAMA ESMALTE',
            'NESTOGENO',
            'KOLESTON',
            'REXONA CLINICAL',
            'FINI GELATINA',
            'REACH FIO DENTAL',
            'GILLETTE MACH 3',
            'O.B.',
            'MAXTON',
            'NEEDS SORO FISIOLOGICO',
            'PHEBO SABONETE',
            'SALON LINE',
            'COLGATE TRIPLA ACAO',
            'GRAVTEST',
            'ENTEROGERMINA',
            'ESPARADRAPO CMR',
            'OFF',
            'BEPANTOL DERMA',
            'SNICKERS',
            'GRANADO BEBE SABONTE LIQUIDO',
            'DOVE BABY',
            'BATON',
            'SOFTYS',
            'ANTHELIOS',
            'ASEPXIA',
        ]
    }


    /**
    * Array of string with eletro products
    * @returns {Array<Objec>}
    */
    static eletro() {
        return [
            'ASPIRADOR DE PÓ',
            'FERRO (TRADICIONAL)',
            'MÁQUINA DE LAVAR ROUPA',
            'BEBEDOURO',
            'MIXER',
            'ESPREMEDOR DE FRUTAS',
            'LIQUIDIFICADOR',
            'BATEDEIRA',
            'SANDUICHEIRA',
            'TORRADEIRA',
            'FORNINHO ELÉTRICO',
            'MÁQUINA DE LAVAR LOUÇAS',
            'GELADEIRA (COM FREEZER)',
            'FOGÃO',
            'COIFA',
            'VENTILADOR ',
            'CAFETEIRA',
            'TELEFONE',
            'ASPIRADOR DE PÓ PORTÁTIL',
            'FERRO Á VAPOR VERTICAL',
            'ADEGA CLIMATIZADA',
        ]
    }

    /**
    * Array of string with marker products
    * @returns {Array<Objec>}
    */
    static pcMarket() {
        return ['Adaptador',
            'Cabo',
            'Caixa de som',
            'Cartucho Compátivel',
            'Cartucho Canon',
            'Cartucho Epson',
            'Cartucho HP',
            'Cartucho Lexmark',
            'Estabilizador',
            'Etiqueta Ink jet',
            'Etiqueta matricial',
            'Filtro de linha',
            'Fita dat',
            'Fita para impressora',
            'Fita para PDV',
            'Fone de ouvido',
            'Formulário contínuo',
            'Fonte',
            'Joystick',
            'Mouse',
            'Mouse pad',
            'MP3',
            'MP4',
            'No-break',
            'Papel para Ink Jet /Laser',
            'Papel fotográfico',
            'Papel para ploter',
            'Pasta para formulário contínuo',
            'Pen drive',
            'Porta cd',
            'Porta CPU',
            'Protetor de tela',
            'Teclado',
            'Toner HP',
            'Toner Lexmark',
            'Transparências',
            'Web cam',
            'Monitor',
            'Fonte',
            'Cabo USB',
            'Memoria RAM',
            'SSD',
            'Gabinete',
            'CPU'
        ]
    }

    /**
    * return array o array with string
    * @returns {Array<array>}
    */
    static pc() {
        return [
            [
                'Intel Core i5-10210U (10ª geração);',
                'SSD de 512GB;',
                '8GB de memória RAM;',
                'Tela de 15.6" com resolução HD;',
                'Windows 10;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Intel Core i3 1115G4 (11ª geração);',
                '4GB memória RAM DDR4;',
                'SSD de 256GB de armazenamento;',
                'Tela LED HD de 15.6";',
                'Windows 10;',
                'Duas portas USB 3.1 Gen 1 e uma porta USB 2.0;',
                'HDMI.',
            ],
            [
                'Intel Core i7-10510U (10ª geração);',
                '8GB de memória RAM;',
                'Placa de vídeo dedicada NVIDIA GeForce MX110 de 2GB;',
                'HDD de 1TB;',
                'SSD de 128GB;',
                'Tela LED de 15.6" HD antirreflexo;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'Windows 10;',
                'HDMI.',
            ],
            [
                'Intel i5-10210U (10ª geração);',
                '8GB de memória RAM DDR4;',
                '1TB de HDD;',
                'Tela LCD Full HD de 15.6" antirreflexo;',
                'Uma porta USB 2.0 e três portas USB 3.0;',
                'Windows 10;',
                'HDMI.',
            ],
            [
                'Intel i7 1165G7 (11ª geração);',
                '8GB de memória RAM DDR4;',
                'SSD de 256GB;',
                'Tela antireflexo Full HD de 15.6";',
                'Windows 10;',
                'Duas portas USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Celeron;',
                '4GB de memória RAM;',
                'SSD de 64GB;',
                'Tela Full HD 13.3";',
                'Windows 10;',
                'Uma porta USB 2.0 e uma porta USB 3.0;',
                'HDMI.',
            ],
            [
                'Intel Core i5-10210U (10ª geração);',
                '8GB de memória RAM DDR4;',
                'HDD de 1TB;',
                'Windows 10;',
                'Tela de 15.6" NanoEdge;',
                'Duas portas USB 2.0;',
                'HDMI.',
            ],
            [
                'Intel i7 11800H (11ª geração);',
                'NVIDIA GeForce RTX 3060 6GB GDDR6;',
                'SSD de 512GB;',
                '16GB de memória RAM DDR4;',
                'Tela de 15.6" Full HD;',
                'Duas portas USB 2.0 e uma porta USB 3.0;',
                'Windows 10;',
                'HDMI.',
            ]
        ]
    }

    /**
    * Array of string with marker products
    * @returns {Array<string>}
    */
    static clothes() {
        return [
            'Camiseta',
            'Camisa',
            'Camisa gola polo',
            'Camisola',
            'Camisa de manga comprida',
            'Camisa de manga curta',
            'Jaqueta',
            'Jaqueta jeans',
            'Croped',
            'Baby look',
            'Casaco',
            'Casaco moletom',
            'Cueca',
            'Calcinha',
            'Cueca box',
            'Bermuda',
            'Short',
            'Calça',
            'Calça jeans',
            'Meia',
            'Boné',
            'Gorro',
            'Boina',
            'Saia',
            'Sutiã',
            'Tomara-que-caia'
        ]
    }

}

module.exports = MarketHelpers