'use strict'

class SocialNetworkHelpers {

    static positivesComment() {
        return [
            "Ótimo trabalho!|Absolutamente fantástico! Tenha um bom dia! 😀",
            "Que incrível!, Adoreii!, Que legal! 🤩",
            "Amei isso! Realmente encantador!, maravilhoso!, incrível!☺",
            "Amei os cores, composição, detalhes! Desejo-lhe um dia fantástico!☺",
            "Amei isso! Continue com seu grande, bom, excelente trabalho!😍",
            "Oi, Olá, Oii Bela postagem, já apertei o amei.",
            "Boa postagem!, Gostei muito, Maravilhoso! Tenha um bom dia, semana, momento",
            "Ótimo!, Legal!, Realmente interessante! Gostei muito; tenha um bom dia, semana, mês",
            "Continue assim!, Muito bem!, Postagem incrível!",
            "Inspirador!, Showww!, Impressionante!, Muito lindo! É isso aí!😄",
            "Gostei muito!, Tá ótimo!, Top de linha! Atééé!😌",
            "Oiee, Oiii, Olá, gostei do seu conteúdo!, post!, trabalho!, ",
            "Inspirador sua postagem!, Showww esse post!, ",
            "Que conteúdo bacana você tem!, Muito lindo! 😄",
            "Genial! Muito legal!, incrível!, maravilhoso!😉",
            "Essa publi é para qual marca de xampu?",
            "Você fica ainda mais lindo(a) quando sorri.",
            "Toda vez que pergunto a Deus sobre a pessoa mais bonita do mundo, Ele me mostra o seu perfil no Instagram.",
            "Definitivamente, nada pode te parar.",
            "Você espalha boas vibrações por onde passa.",
            "Seria essa a oitava maravilha do mundo?",
            "Olá, Miss/Mister Mundo!",
            "Por onde começo a te elogiar? 🤔",
            "Quem resiste a esse senso de humor?",
            "Para qual revista você está posando? 📸",
            "Pessoal, eu não sabia que seguia a(o) xxxx! (substituir xxxx pelo nome de uma celebridade)",
            "É oficial: essa foto ganhou o título de mais fofa do ano. 🥰",
            "Pensava que perfeição não existia. Até eu ver a sua foto.",
            "Como é ser essa pessoa tão linda?",
            "Podre de chique! ✨",
            "Como vou parar de pensar em você pelo resto do dia após essa foto?",
            "Cada post seu é um verdadeiro evento, né?",
            "Você é 'hors-concours' no quesito beleza.",
            "A sua energia é diferente, especial.",
            "Sem defeitos que fala, né?",
            "Essa foto elevou meus níveis de dopamina!",
            "Clique de milhões, hein?",
            "O fofurômetro explodiu!",
            "Esse post melhorou o meu dia 🥰",
            "Estou sem palavras!",
            "Como faz para curtir isso duas vezes?",
            "Que cenário incrível!",
            "Que luz perfeita! Parece foto profissional 👏👏",
            "Tentando adivinhar no que você está pensando.",
            "O brilho nos seus olhos me inspira.",
            "Essa foto me fez sorrir 😊",
            "A felicidade cai bem demais em você.",
            "O Instagram deveria te pagar por essa foto!",
            "O que você estava bebendo?",
            "Personificação da alegria!",
            "Olha quem finalmente atualizou o feed!",
            "Cataploft! Esse foi o som de quando caí no chão após ver essa foto.",
            "Ainda não consegui superar a sua última foto e você já vem com essa?",
            "Que seus dias sejam de sinais abertos, filas rápidas no supermercado e bolos com calda de chocolate.",
            "Por um momento, pensei estar olhando para uma pintura.",
            "Minhas pessoas favoritas no mundo na mesma foto!",
            "Essa foto transmite uma paz...",
            "Arco-íris, unicórnios, fadas e pirulitos. Essa é a vibe dessa foto!",
            "Smi:)e (forma estilizada da palavra smile, que, em inglês, significa sorria ou sorriso)",
            "Tudo o que eu queria para hoje.",
            "O que o Instagram está esperando para tornar a sua conta verificada?",
            "Eu juro que ela acorda assim, minha gente.",
            "Minha amiga é maravilhosa!",
            "Essa é a foto de divulgação da próxima princesa da Disney? 👑",
            "Tenho memórias incríveis desse dia!",
            "Preciso dessa roupa emprestada!",
            "Saibam que a melhor amiga do mundo já tem uma melhor amiga, ok?",
            "Deusa acessível!",
            "Família que eu escolhi 😊",
            "A distância significa muito pouco quando alguém significa muito.",
            "Quem de nós que é a má influência? 🙊",
            "Conta para os(as) reles mortais como é ser incrível?",
            "Posso ser você quando crescer?",
            "📣 Ela está solteira, hein, pessoal?!",
            "Preciso a-go-ra de um tutorial dessa maquiagem!",
            "Seu cabelo ficou maravilhoso!",
            "Ok, definitivamente, preciso seguir os seus conselhos sobre cuidados com a pele.",
            "Sou seu/sua fã número um!",
            "Você é gigante!",
            "A senhora nunca decepciona, não é mesmo?",
            "A história dessa noite daria um livro 🤣",
            "Linda, humilde, batalhadora e minha amiga 💖",
            "Só falta uma coisa para essa foto ficar perfeita: eu! 😜",
            "Tenho quase certeza de que é ilegal ser tão bonito(a) assim. 🚨",
            "Você é tão bonito(a) por dentro quanto é por fora?",
            "Poderia passar o dia inteiro olhando o seu feed.",
            "Esse rosto foi feito para tirar selfies.",
            "Quando um olhar fala mais do que mil palavras…",
            "Vou sonhar com essa foto.",
            "É possível se apaixonar por uma foto? 🤗",
            "Agradeço, em nome da humanidade, por nos abençoar com essa selfie 🙏",
            "Queria poder dar um “superlike” nessa foto. ❤️",
            "Claramente gato(a) sem nenhum esforço.",
            "Como você ainda está solteira(o)? 🤔",
            "Emoji de coraçãozinhos nos olhos para você.",
            "Você conseguiu esgotar meu repertório de elogios.",
            "Deve ser difícil não gostar de você, né?",
            "Essa merece virar foto de perfil!",
            "Quase ninguém sabe, mas o interior é a sua parte mais linda.",
            "Aposto que pessoalmente você é ainda mais bonito(a).",
            "Seu feed é eita atrás de eita, hein?"
        ]
    }

    static negativeComments() {
        return [
            "Infelizmente não gostei!",
            "Poderia melhorar, achei bem superficial",
            "Não gosto deste tipo de conteudo, quem sabe fica para próxima",
            "Deus me livre!",
            "Tem que melhorar muito, está sem sal",
            "Embora tenha tiro paciência, nao gostei",
            "Péssimo conteudo, parando de seguir aqui",
            "Perdi esse tempo da minha vida vendo isso...credo",
            "Acredito que você deveria parar de postar esse conteudo",
            "Vou procurar algo melhor para assistir",
            "Péssimo... parando seguir",
            "Ai ai ai... não acredito que perdi meu tempo vendo isso!",
            "Péssimo!",
            "Não gostei",
            "Sem graça",
            "Prefiro ver outra coisa"
        ]
    }


    static sportText() {
        return [
            "Neste domingo será conhecido o vencedor de 2023 do Campeonato Carioca. Flamengo e Fluminense se enfrentam no Maracanã tentando adicionar mais um troféu à galeria em suas sedes. Quem perder, porém, engrossará outra lista: a dos vice-campeões do Carioca.",
            "Atualmente, o Flamengo lidera a lista: ficou em segundo lugar no Carioca por 34 vezes na história, seguido por Vasco, com 26, Fluminense, com 25, e Botafogo, com 21.",
            "O Flamengo pode ter desfalque de última hora para a decisão do Carioca, marcada para domingo, às 18h, no Maracanã, contra o Fluminense. O volante Vidal deu entrada em hospital na Zona Oeste do Rio de Janeiro no início da madrugada deste sábado (0h50min) apresentando edema, dores e infecção no cotovelo esquerdo.",
            "A informação foi publicada primeiramente pelo jornalista Guilherme Pinheiro, do canal Flazoeiro.",
            "Embora o time da primeira partida da final seja o mais provável para o jogo de domingo, treinador repete estratégia que tem utilizado desde a derrota para o mesmo Tricolor",
            "A exemplo do que praticou nas últimas quatro semanas, especialmente após a derrota para o Fluminense na decisão da Taça Guanabara, Vítor Pereira não montou time no treinamento desta sexta-feira, o penúltimo antes do Fla-Flu que apontará o campeão carioca de 2023.",
            "No início do trabalho, Vítor por vezes treinava o time que pretendia levar a campo nos jogos, especialmente em semanas cheias. Agora, incomodado com o vazamento das escalações, faz diferentes dinâmicas durante os treinos, mas não indica possíveis formações em hipótese alguma.",
            "Ciente de que está sob pressão mais uma vez, o português não quer dar armas a Fernando Diniz, com quem vem travando duelos decisivos desde o ano passado, quando dirigia o Corinthians.",
            "Para confirmar o seu 38º título carioca, o Flamengo pode até perder por um gol de diferença. No primeiro jogo, Ayrton Lucas e Pedro marcaram na vitória por 2 a 0. Neste sábado, a equipe faz sua última atividade antes da finalíssima estadual.",
            "Dispensas, transferências, sondagens e busca por reforços; saiba tudo sobre as movimentações do clube no mercado",
            "Com uma base sólida que ajudou o Flamengo a conquistar o tri da Libertadores e o tetra da Copa do Brasil, a diretoria irá ao mercado para buscar nomes de peso. Dentro do planejamento do comando do futebol também estão previstas vendas, mas a expectativa é de que as saídas aconteçam sobretudo na janela do meio do ano, a principal da Europa.",
            "Ângelo: atacante de 19 anos é desejo antigo do Flamengo e tem aprovação de Vítor Pereira. Canhoto e jogador que atua aberto pela direita, o jovem foi formado na base do Santos, clube que defende até hoje. O Rubro-Negro fez proposta de 12 milhões de euros para tirá-lo da Vila.",
            "Matheus Uribe: volante de 31 anos, o colombiano é titular absoluto do Porto e jogou em 37 das 41 partidas da equipe na temporada. Destro e de 1,80m de altura, ele pode assinar pré-contrato com outra equipe, já que seu vínculo com o Dragão é válido até 30 de junho.",
            "Vitor Pereira: depois de anunciar sua saída do Corinthians, o português entrou na mira do Flamengo e chegou a um acordo para ser o técnico da equipe em 2023. Ele foi anunciado no dia 13 de dezembro e inicia o trabalho no Ninho do Urubu no dia 2 de janeiro.",
            "Agustín Rossi: o goleiro do Boca Juniors assinou pré-contrato com o Flamengo, no entanto, a equipe argentina emprestou Rossi ao Al Nassr, da Arábia Saudita, até o dia 30 de junho. A partir do dia 1º de julho, o defensor iniciará a trajetória no clube carioca, com contrato válido até dezembro de 2027.",
            "Dorival Júnior: magoado com o fato de o Flamengo ter aberto conversas com Vitor Pereira, Dorival anunciou sua saída do clube. O vídeo em que comunicou que não permaneceria foi feito momentos após Bruno Spindel entrar em contato com seu agente, Edson Khodor.",
            "Diego Alves: no clube desde julho de 2017, o goleiro de 37 anos não renovará contrato. Deixa o clube com duas Libertadores, dois Brasileiros, uma Copa do Brasil, uma Recopa Sul-Americana, duas Supercopas do Brasil e três estaduais. Disputou 217 jogos pelo Flamengo e se despediu contra o Avaí.",
            "Diego: diferente do xará que joga no gol, o camisa 10 não apenas está se despedindo do Flamengo, mas também do futebol profissional. Contra o Avaí, Diego concluiu sua sétima temporada (estreou em agosto de 2016) e encerra sua carreira. Foram 289 jogos, 44 gols marcados e 12 títulos conquistados, todos os que Diego Alves conquistou e mais o Carioca de 2017.",
            "Thiaguinho: após passar a última temporada emprestado ao Houston Dynamo, dos Estados Unidos, o atacante de 21 anos foi novamente negociado pelo Flamengo. Ele ficará até o final de 2023 no CSA, e disputará a Série B pelo clube alagoano.",
            "João Gomes: depois e encaminhar acerto com o Wolverhampton, o Flamengo recebeu proposta mais vantajosa do Lyon. O volante deve seguir o ano longe da Gávea, mas ainda não tem destino certo. Os valores estão na casa dos R$ 100 milhões.",
            "Hugo Souza: o goleiro recusou proposta do Vissel Kobe, do Japão, e recebeu sondagem do Benfica. Enquanto espera a definição do futuro, Hugo segue nos treinos no Ninho do Urubu e, inclusive, foi relacionado para a partida contra o Nova Iguaçu.",
            "Sport x CRB e ABC x Náutico se enfrentam de um lado da chave, enquanto Ceará x Sergipe e Fortaleza x Ferroviário buscam a outra vaga na final; confira jogos do mata-mata",
            "ABC, Náutico e Sergipe se juntam a Ceará, Sport, Fortaleza, Ferroviário e CRB entre os times que vão às quartas de final da Copa do Nordeste. Além de determinar os oito classificados, a última rodada da competição, nesta quarta-feira, definiu seus confrontos de quartas de final, assim como os cruzamentos até a grande decisão.",
            "Dono da melhor campanha da primeira fase com a vitória sobre o CSA em Maceió, o Sport recebe o CRB. O vencedor desse duelo enfrenta quem levar a melhor de ABC x Náutico. Do outro lado da chave, Ceará x Sergipe duelam em Natal, enquanto Fortaleza x Ferroviário fazem clássico cearense.",
            "As quartas serão disputadas no próximo fim de semana, com datas e horários a serem definidos. O Santa Cruz, com a derrota para o Fortaleza, foi o último time a ser eliminado da competição. Antes dele, Bahia, Campinense, CSA, Sampaio Corrêa, Atlético-BA, Vitória e Fluminense-PI já tinham dado adeus.",
            "Quartas e semis serão disputadas em jogo único e, em caso de empate, a vaga é decidida na disputa de pênaltis. Os times de melhor campanha jogam em casa. Já a final será disputada em ida e volta e, em caso de igualdade nos pontos e, posteriormente, no saldo de gols do confronto, a decisão do título vai para os pênaltis.",
            "Organizada cobra volta do visual antigo, após o clube alterar expressões, roupa e cor das mascotes: 'Ronaldo, gordão, devolve o Raposão'; mudança repercutiu nas redes sociais e rendeu memes",
            "Integrantes de uma das maiores organizadas do Cruzeiro se reuniram em um protesto em frente à Toca da Raposa, nesta quinta-feira. Com bandeiras e foguetes, o grupo se manifestou contra a troca da identidade visual do mascote, o Raposão. Gritos pediam para Ronaldo retomar com o visual antigo do símbolo do clube.",
            "Mais cedo, ainda nesta quinta, várias organizadas se pronunciaram nas redes sociais contra a mudança na identidade do mascote. O Cruzeiro reformou a roupa, a cor e a expressão dos dois símbolos do clube, Raposão e Raposinho. Veja abaixo o antes e depois:",
            "O Raposão é o maior mascote do Brasil, e sempre se fez presente pelo carisma, força e seriedade, tudo ao mesmo tempo. É inadmissível as mudanças feitas no mascote, e só corroboram aquilo que estamos vendo faz tempo: a falta de sinergia com o torcedor, que agora é mero cliente, e principalmente a falta de conhecimento de muitos que hoje estão no Clube sobre o Cruzeiro e principalmente a própria torcida - disse parte da nota",
            "Casa de apostas Esportes da Sorte assina contrato pelas próximos três anos e vai pagar bonificação por metas alcançadas",
            "O vínculo é válido por três anos, com bonificação por metas alcançadas, entre eles participações em Libertadores e títulos. O diretor de patrimônio do Athletico, Márcio Lara, afirmou que é 'um patrocínio com valor significativo'.",
            "- O contrato estabelece metas financeiras para cada competição que o Athletico está disputando. Temos metas se formos campeões da Libertadores, outra meta se ganharmos o Campeonato Brasileiro e outra para a Copa do Brasil - explicou Márcio Lara.",
            "Para que o acordo com a nova patrocinadora máster fosse fechado, o Athletico precisou romper o contrato com a Betsson, que estampava a marca nas costas do uniforme do time masculino e na camisa da equipe feminina.",
            "- Nós tomamos todas as medidas legais e possíveis de forma amigável. Foi uma questão negocial e com uma decisão do Athletico de fechar o contrato máster com uma outra empresa do mesmo ramo. Não estamos vendo de nenhum tipo de situação que venha nos trazer algum problema no futuro - afirmou Márcio Lara.",
            "A estreia do novo patrocinador máster do Athletico acontece na partida de domingo, às 16h, na Arena da Baixada, pela semifinal do Campeonato Paranaense.",
            "O técnico do Palmeiras, Abel Ferreira, com outras sete pessoas, é alvo de uma cobrança milionária na Justiça por parte de um ex-sócio numa empresa do ramo imobiliário no Rio Grande do Norte.",
            "Pedro Sousa cobra deles a quantia de R$ 3.845.057,50. O autor da ação argumenta que foi retirado ilegalmente da posição de administrador da empresa, assim como da própria sociedade, numa assembleia de sócios realizada – segundo ele – de maneira irregular.",
            "O caso foi revelado pelo jornal português 'A Bola' nesta sexta-feira, e confirmado pelo ge a partir de documentos e conversas com pessoas com conhecimento do caso.",
            "O jornal 'A Bola' noticiou ainda que Abel teria sido alvo de acusações na esfera criminal. Na ação de cobrança, a que o ge teve acesso, Pedro Sousa cita a existência de um procedimento de investigação na Polícia Civil potiguar, algo que o técnico negou em nota enviada à imprensa.",
            "– É completamente falso que eu tenha sido acusado ou vá ser julgado em qualquer processo crime. Deste modo, qualquer notícia em que seja dito o contrário é completamente falsa e ofensiva da minha imagem e bom nome enquanto pessoa, responsabilizando todos aqueles que a criaram ou a divulgaram.",
            "Os advogados do técnico ainda não comentaram especificamente sobre a ação cível – com pedido de indenização – que corre na Justiça do Rio Grande do Norte.",
            "A empresa foi constituída em 2012, um ano depois de Abel Ferreira ter encerrado sua carreira de jogador, e oito anos antes de ele ter vindo trabalhar no Brasil como técnico do Palmeiras.",
            "O registro da empresa na Junta Comercial do Rio Grande do Norte, consultado pela reportagem nesta sexta-feira, mostra que Abel Ferreira ainda é sócio – embora tenha nomeado um procurador como seu representante legal.",
            "Pedro Sousa, o autor da ação contra Abel, foi procurado pela reportagem, mas afirmou que não gostaria de falar sobre o caso. Ele já apresentou um recurso para tentar ser reintegrado à empresa, mas seu pedido foi negado pela Justiça.",
            "'A Sociedade Esportiva Palmeiras vem a público demonstrar apoio ao técnico Abel Ferreira, profissional e ser humano de insuspeitos caráter e reputação. O clube manifesta a sua convicção de que a verdade prevalecerá sobre as mentiras veiculadas nesta sexta-feira (24)'."
        ]
    }

}

module.exports = SocialNetworkHelpers;