'use strict'

class SocialNetworkHelpers {

    static positivesComment() {
        return [
            "Ótimo trabalho!|Absolutamente fantástico! Tenha um bom dia! 😀",
            "Que incrível!, Adoreii!, Que legal! 🤩",
            "Amei isso! Realmente encantador!, maravilhoso!, incrível!☺",
            "Amei os cores, composição, detalhes! Desejo-lhe um dia fantástico!☺",
            "Amei isso! Continue com seu grande, bom, excelente trabalho!😍",
            "Oi, Olá, Oii Bela postagem, já apertei o amei.",
            "Boa postagem!, Gostei muito, Maravilhoso! Tenha um bom dia, semana, momento",
            "Ótimo!, Legal!, Realmente interessante! Gostei muito; tenha um bom dia, semana, mês",
            "Continue assim!, Muito bem!, Postagem incrível!",
            "Inspirador!, Showww!, Impressionante!, Muito lindo! É isso aí!😄",
            "Gostei muito!, Tá ótimo!, Top de linha! Atééé!😌",
            "Oiee, Oiii, Olá, gostei do seu conteúdo!, post!, trabalho!, ",
            "Inspirador sua postagem!, Showww esse post!, ",
            "Que conteúdo bacana você tem!, Muito lindo! 😄",
            "Genial! Muito legal!, incrível!, maravilhoso!😉",
            "Essa publi é para qual marca de xampu?",
            "Você fica ainda mais lindo(a) quando sorri.",
            "Toda vez que pergunto a Deus sobre a pessoa mais bonita do mundo, Ele me mostra o seu perfil no Instagram.",
            "Definitivamente, nada pode te parar.",
            "Você espalha boas vibrações por onde passa.",
            "Seria essa a oitava maravilha do mundo?",
            "Olá, Miss/Mister Mundo!",
            "Por onde começo a te elogiar? 🤔",
            "Quem resiste a esse senso de humor?",
            "Para qual revista você está posando? 📸",
            "Pessoal, eu não sabia que seguia a(o) xxxx! (substituir xxxx pelo nome de uma celebridade)",
            "É oficial: essa foto ganhou o título de mais fofa do ano. 🥰",
            "Pensava que perfeição não existia. Até eu ver a sua foto.",
            "Como é ser essa pessoa tão linda?",
            "Podre de chique! ✨",
            "Como vou parar de pensar em você pelo resto do dia após essa foto?",
            "Cada post seu é um verdadeiro evento, né?",
            "Você é 'hors-concours' no quesito beleza.",
            "A sua energia é diferente, especial.",
            "Sem defeitos que fala, né?",
            "Essa foto elevou meus níveis de dopamina!",
            "Clique de milhões, hein?",
            "O fofurômetro explodiu!",
            "Esse post melhorou o meu dia 🥰",
            "Estou sem palavras!",
            "Como faz para curtir isso duas vezes?",
            "Que cenário incrível!",
            "Que luz perfeita! Parece foto profissional 👏👏",
            "Tentando adivinhar no que você está pensando.",
            "O brilho nos seus olhos me inspira.",
            "Essa foto me fez sorrir 😊",
            "A felicidade cai bem demais em você.",
            "O Instagram deveria te pagar por essa foto!",
            "O que você estava bebendo?",
            "Personificação da alegria!",
            "Olha quem finalmente atualizou o feed!",
            "Cataploft! Esse foi o som de quando caí no chão após ver essa foto.",
            "Ainda não consegui superar a sua última foto e você já vem com essa?",
            "Que seus dias sejam de sinais abertos, filas rápidas no supermercado e bolos com calda de chocolate.",
            "Por um momento, pensei estar olhando para uma pintura.",
            "Minhas pessoas favoritas no mundo na mesma foto!",
            "Essa foto transmite uma paz...",
            "Arco-íris, unicórnios, fadas e pirulitos. Essa é a vibe dessa foto!",
            "Smi:)e (forma estilizada da palavra smile, que, em inglês, significa sorria ou sorriso)",
            "Tudo o que eu queria para hoje.",
            "O que o Instagram está esperando para tornar a sua conta verificada?",
            "Eu juro que ela acorda assim, minha gente.",
            "Minha amiga é maravilhosa!",
            "Essa é a foto de divulgação da próxima princesa da Disney? 👑",
            "Tenho memórias incríveis desse dia!",
            "Preciso dessa roupa emprestada!",
            "Saibam que a melhor amiga do mundo já tem uma melhor amiga, ok?",
            "Deusa acessível!",
            "Família que eu escolhi 😊",
            "A distância significa muito pouco quando alguém significa muito.",
            "Quem de nós que é a má influência? 🙊",
            "Conta para os(as) reles mortais como é ser incrível?",
            "Posso ser você quando crescer?",
            "📣 Ela está solteira, hein, pessoal?!",
            "Preciso a-go-ra de um tutorial dessa maquiagem!",
            "Seu cabelo ficou maravilhoso!",
            "Ok, definitivamente, preciso seguir os seus conselhos sobre cuidados com a pele.",
            "Sou seu/sua fã número um!",
            "Você é gigante!",
            "A senhora nunca decepciona, não é mesmo?",
            "A história dessa noite daria um livro 🤣",
            "Linda, humilde, batalhadora e minha amiga 💖",
            "Só falta uma coisa para essa foto ficar perfeita: eu! 😜",
            "Tenho quase certeza de que é ilegal ser tão bonito(a) assim. 🚨",
            "Você é tão bonito(a) por dentro quanto é por fora?",
            "Poderia passar o dia inteiro olhando o seu feed.",
            "Esse rosto foi feito para tirar selfies.",
            "Quando um olhar fala mais do que mil palavras…",
            "Vou sonhar com essa foto.",
            "É possível se apaixonar por uma foto? 🤗",
            "Agradeço, em nome da humanidade, por nos abençoar com essa selfie 🙏",
            "Queria poder dar um “superlike” nessa foto. ❤️",
            "Claramente gato(a) sem nenhum esforço.",
            "Como você ainda está solteira(o)? 🤔",
            "Emoji de coraçãozinhos nos olhos para você.",
            "Você conseguiu esgotar meu repertório de elogios.",
            "Deve ser difícil não gostar de você, né?",
            "Essa merece virar foto de perfil!",
            "Quase ninguém sabe, mas o interior é a sua parte mais linda.",
            "Aposto que pessoalmente você é ainda mais bonito(a).",
            "Seu feed é eita atrás de eita, hein?"
        ]
    }

    static negativeComments() {
        return [
            "Infelizmente não gostei!",
            "Poderia melhorar, achei bem superficial",
            "Não gosto deste tipo de conteudo, quem sabe fica para próxima",
            "Deus me livre!",
            "Tem que melhorar muito, está sem sal",
            "Embora tenha tiro paciência, nao gostei",
            "Péssimo conteudo, parando de seguir aqui",
            "Perdi esse tempo da minha vida vendo isso...credo",
            "Acredito que você deveria parar de postar esse conteudo",
            "Vou procurar algo melhor para assistir",
            "Péssimo... parando seguir",
            "Ai ai ai... não acredito que perdi meu tempo vendo isso!",
            "Péssimo!",
            "Não gostei",
            "Sem graça",
            "Prefiro ver outra coisa"
        ]
    }


    static sportText() {
        return [
            "Neste domingo será conhecido o vencedor de 2023 do Campeonato Carioca. Flamengo e Fluminense se enfrentam no Maracanã tentando adicionar mais um troféu à galeria em suas sedes. Quem perder, porém, engrossará outra lista: a dos vice-campeões do Carioca.",
            "Atualmente, o Flamengo lidera a lista: ficou em segundo lugar no Carioca por 34 vezes na história, seguido por Vasco, com 26, Fluminense, com 25, e Botafogo, com 21.",
            "O Flamengo pode ter desfalque de última hora para a decisão do Carioca, marcada para domingo, às 18h, no Maracanã, contra o Fluminense. O volante Vidal deu entrada em hospital na Zona Oeste do Rio de Janeiro no início da madrugada deste sábado (0h50min) apresentando edema, dores e infecção no cotovelo esquerdo.",
            "A informação foi publicada primeiramente pelo jornalista Guilherme Pinheiro, do canal Flazoeiro.",
            "Embora o time da primeira partida da final seja o mais provável para o jogo de domingo, treinador repete estratégia que tem utilizado desde a derrota para o mesmo Tricolor",
            "A exemplo do que praticou nas últimas quatro semanas, especialmente após a derrota para o Fluminense na decisão da Taça Guanabara, Vítor Pereira não montou time no treinamento desta sexta-feira, o penúltimo antes do Fla-Flu que apontará o campeão carioca de 2023.",
            "No início do trabalho, Vítor por vezes treinava o time que pretendia levar a campo nos jogos, especialmente em semanas cheias. Agora, incomodado com o vazamento das escalações, faz diferentes dinâmicas durante os treinos, mas não indica possíveis formações em hipótese alguma.",
            "Ciente de que está sob pressão mais uma vez, o português não quer dar armas a Fernando Diniz, com quem vem travando duelos decisivos desde o ano passado, quando dirigia o Corinthians.",
            "Para confirmar o seu 38º título carioca, o Flamengo pode até perder por um gol de diferença. No primeiro jogo, Ayrton Lucas e Pedro marcaram na vitória por 2 a 0. Neste sábado, a equipe faz sua última atividade antes da finalíssima estadual.",
            "Dispensas, transferências, sondagens e busca por reforços; saiba tudo sobre as movimentações do clube no mercado",
            "Com uma base sólida que ajudou o Flamengo a conquistar o tri da Libertadores e o tetra da Copa do Brasil, a diretoria irá ao mercado para buscar nomes de peso. Dentro do planejamento do comando do futebol também estão previstas vendas, mas a expectativa é de que as saídas aconteçam sobretudo na janela do meio do ano, a principal da Europa.",
            "Ângelo: atacante de 19 anos é desejo antigo do Flamengo e tem aprovação de Vítor Pereira. Canhoto e jogador que atua aberto pela direita, o jovem foi formado na base do Santos, clube que defende até hoje. O Rubro-Negro fez proposta de 12 milhões de euros para tirá-lo da Vila.",
            "Matheus Uribe: volante de 31 anos, o colombiano é titular absoluto do Porto e jogou em 37 das 41 partidas da equipe na temporada. Destro e de 1,80m de altura, ele pode assinar pré-contrato com outra equipe, já que seu vínculo com o Dragão é válido até 30 de junho.",
            "Vitor Pereira: depois de anunciar sua saída do Corinthians, o português entrou na mira do Flamengo e chegou a um acordo para ser o técnico da equipe em 2023. Ele foi anunciado no dia 13 de dezembro e inicia o trabalho no Ninho do Urubu no dia 2 de janeiro.",
            "Agustín Rossi: o goleiro do Boca Juniors assinou pré-contrato com o Flamengo, no entanto, a equipe argentina emprestou Rossi ao Al Nassr, da Arábia Saudita, até o dia 30 de junho. A partir do dia 1º de julho, o defensor iniciará a trajetória no clube carioca, com contrato válido até dezembro de 2027.",
            "Dorival Júnior: magoado com o fato de o Flamengo ter aberto conversas com Vitor Pereira, Dorival anunciou sua saída do clube. O vídeo em que comunicou que não permaneceria foi feito momentos após Bruno Spindel entrar em contato com seu agente, Edson Khodor.",
            "Diego Alves: no clube desde julho de 2017, o goleiro de 37 anos não renovará contrato. Deixa o clube com duas Libertadores, dois Brasileiros, uma Copa do Brasil, uma Recopa Sul-Americana, duas Supercopas do Brasil e três estaduais. Disputou 217 jogos pelo Flamengo e se despediu contra o Avaí.",
            "Diego: diferente do xará que joga no gol, o camisa 10 não apenas está se despedindo do Flamengo, mas também do futebol profissional. Contra o Avaí, Diego concluiu sua sétima temporada (estreou em agosto de 2016) e encerra sua carreira. Foram 289 jogos, 44 gols marcados e 12 títulos conquistados, todos os que Diego Alves conquistou e mais o Carioca de 2017.",
            "Thiaguinho: após passar a última temporada emprestado ao Houston Dynamo, dos Estados Unidos, o atacante de 21 anos foi novamente negociado pelo Flamengo. Ele ficará até o final de 2023 no CSA, e disputará a Série B pelo clube alagoano.",
            "João Gomes: depois e encaminhar acerto com o Wolverhampton, o Flamengo recebeu proposta mais vantajosa do Lyon. O volante deve seguir o ano longe da Gávea, mas ainda não tem destino certo. Os valores estão na casa dos R$ 100 milhões.",
            "Hugo Souza: o goleiro recusou proposta do Vissel Kobe, do Japão, e recebeu sondagem do Benfica. Enquanto espera a definição do futuro, Hugo segue nos treinos no Ninho do Urubu e, inclusive, foi relacionado para a partida contra o Nova Iguaçu.",
            "Sport x CRB e ABC x Náutico se enfrentam de um lado da chave, enquanto Ceará x Sergipe e Fortaleza x Ferroviário buscam a outra vaga na final; confira jogos do mata-mata",
            "ABC, Náutico e Sergipe se juntam a Ceará, Sport, Fortaleza, Ferroviário e CRB entre os times que vão às quartas de final da Copa do Nordeste. Além de determinar os oito classificados, a última rodada da competição, nesta quarta-feira, definiu seus confrontos de quartas de final, assim como os cruzamentos até a grande decisão.",
            "Dono da melhor campanha da primeira fase com a vitória sobre o CSA em Maceió, o Sport recebe o CRB. O vencedor desse duelo enfrenta quem levar a melhor de ABC x Náutico. Do outro lado da chave, Ceará x Sergipe duelam em Natal, enquanto Fortaleza x Ferroviário fazem clássico cearense.",
            "As quartas serão disputadas no próximo fim de semana, com datas e horários a serem definidos. O Santa Cruz, com a derrota para o Fortaleza, foi o último time a ser eliminado da competição. Antes dele, Bahia, Campinense, CSA, Sampaio Corrêa, Atlético-BA, Vitória e Fluminense-PI já tinham dado adeus.",
            "Quartas e semis serão disputadas em jogo único e, em caso de empate, a vaga é decidida na disputa de pênaltis. Os times de melhor campanha jogam em casa. Já a final será disputada em ida e volta e, em caso de igualdade nos pontos e, posteriormente, no saldo de gols do confronto, a decisão do título vai para os pênaltis.",
            "Organizada cobra volta do visual antigo, após o clube alterar expressões, roupa e cor das mascotes: 'Ronaldo, gordão, devolve o Raposão'; mudança repercutiu nas redes sociais e rendeu memes",
            "Integrantes de uma das maiores organizadas do Cruzeiro se reuniram em um protesto em frente à Toca da Raposa, nesta quinta-feira. Com bandeiras e foguetes, o grupo se manifestou contra a troca da identidade visual do mascote, o Raposão. Gritos pediam para Ronaldo retomar com o visual antigo do símbolo do clube.",
            "Mais cedo, ainda nesta quinta, várias organizadas se pronunciaram nas redes sociais contra a mudança na identidade do mascote. O Cruzeiro reformou a roupa, a cor e a expressão dos dois símbolos do clube, Raposão e Raposinho. Veja abaixo o antes e depois:",
            "O Raposão é o maior mascote do Brasil, e sempre se fez presente pelo carisma, força e seriedade, tudo ao mesmo tempo. É inadmissível as mudanças feitas no mascote, e só corroboram aquilo que estamos vendo faz tempo: a falta de sinergia com o torcedor, que agora é mero cliente, e principalmente a falta de conhecimento de muitos que hoje estão no Clube sobre o Cruzeiro e principalmente a própria torcida - disse parte da nota",
            "Casa de apostas Esportes da Sorte assina contrato pelas próximos três anos e vai pagar bonificação por metas alcançadas",
            "O vínculo é válido por três anos, com bonificação por metas alcançadas, entre eles participações em Libertadores e títulos. O diretor de patrimônio do Athletico, Márcio Lara, afirmou que é 'um patrocínio com valor significativo'.",
            "- O contrato estabelece metas financeiras para cada competição que o Athletico está disputando. Temos metas se formos campeões da Libertadores, outra meta se ganharmos o Campeonato Brasileiro e outra para a Copa do Brasil - explicou Márcio Lara.",
            "Para que o acordo com a nova patrocinadora máster fosse fechado, o Athletico precisou romper o contrato com a Betsson, que estampava a marca nas costas do uniforme do time masculino e na camisa da equipe feminina.",
            "- Nós tomamos todas as medidas legais e possíveis de forma amigável. Foi uma questão negocial e com uma decisão do Athletico de fechar o contrato máster com uma outra empresa do mesmo ramo. Não estamos vendo de nenhum tipo de situação que venha nos trazer algum problema no futuro - afirmou Márcio Lara.",
            "A estreia do novo patrocinador máster do Athletico acontece na partida de domingo, às 16h, na Arena da Baixada, pela semifinal do Campeonato Paranaense.",
            "O técnico do Palmeiras, Abel Ferreira, com outras sete pessoas, é alvo de uma cobrança milionária na Justiça por parte de um ex-sócio numa empresa do ramo imobiliário no Rio Grande do Norte.",
            "Pedro Sousa cobra deles a quantia de R$ 3.845.057,50. O autor da ação argumenta que foi retirado ilegalmente da posição de administrador da empresa, assim como da própria sociedade, numa assembleia de sócios realizada – segundo ele – de maneira irregular.",
            "O caso foi revelado pelo jornal português 'A Bola' nesta sexta-feira, e confirmado pelo ge a partir de documentos e conversas com pessoas com conhecimento do caso.",
            "O jornal 'A Bola' noticiou ainda que Abel teria sido alvo de acusações na esfera criminal. Na ação de cobrança, a que o ge teve acesso, Pedro Sousa cita a existência de um procedimento de investigação na Polícia Civil potiguar, algo que o técnico negou em nota enviada à imprensa.",
            "– É completamente falso que eu tenha sido acusado ou vá ser julgado em qualquer processo crime. Deste modo, qualquer notícia em que seja dito o contrário é completamente falsa e ofensiva da minha imagem e bom nome enquanto pessoa, responsabilizando todos aqueles que a criaram ou a divulgaram.",
            "Os advogados do técnico ainda não comentaram especificamente sobre a ação cível – com pedido de indenização – que corre na Justiça do Rio Grande do Norte.",
            "A empresa foi constituída em 2012, um ano depois de Abel Ferreira ter encerrado sua carreira de jogador, e oito anos antes de ele ter vindo trabalhar no Brasil como técnico do Palmeiras.",
            "O registro da empresa na Junta Comercial do Rio Grande do Norte, consultado pela reportagem nesta sexta-feira, mostra que Abel Ferreira ainda é sócio – embora tenha nomeado um procurador como seu representante legal.",
            "Pedro Sousa, o autor da ação contra Abel, foi procurado pela reportagem, mas afirmou que não gostaria de falar sobre o caso. Ele já apresentou um recurso para tentar ser reintegrado à empresa, mas seu pedido foi negado pela Justiça.",
            "'A Sociedade Esportiva Palmeiras vem a público demonstrar apoio ao técnico Abel Ferreira, profissional e ser humano de insuspeitos caráter e reputação. O clube manifesta a sua convicção de que a verdade prevalecerá sobre as mentiras veiculadas nesta sexta-feira (24)'."
        ]
    }

    static newsText() {
        return [
            "Entre 2018 e 2022, 592 foram exonerados - mais que batalhões da corporação como o Bope, que tem 400 militares. Dados obtidos pelo g1 mostram queda de punição durante o governo Witzel.",
            "Entre 1º de janeiro e 15 de março de 2023, 40 policiais militares do RJ foram expulsos da corporação. Dados obtidos com exclusividade pelo g1 mostram que esses agentes foram excluídos por crimes como envolvimento com a milícia, extorsão, porte ilegal de armas, homicídios, roubo e receptação.",
            "No estado, há hoje cerca de 40 mil PMs. Entre 2018 e 2022, 592 foram desligados. Isso equivale a um batalhão inteiro: o Bope, por exemplo, tem 400 homens.",
            "Quando o ex-juiz federal Wilson Witzel (então no PSC) assumiu o Palácio Guanabara, as expulsões caíram significativamente: 49 em 2019, 32 em 2020 e 47 em 2021 (veja o que diz Witzel no fim da reportagem).",
            "“Foge ao senso comum que não fosse sabido por estes as atividades escusas conduzidas pelo referido miliciano”, destacou a conclusão do procedimento disciplinar.",
            "Um prédio de quatro andares desabou em um bairro de classe média no centro de Marselha, no sul da França, na madrugada deste domingo (9), e um incêndio atingiu os escombros do imóvel. Durante a manhã, um segundo imóvel vizinho, que tinha sido esvaziado, também desmoronou.",
            "De acordo com Payan, a avaliação é provisória. “Devemos estar preparados para ter vítimas nesta terrível tragédia”, disse Payan.",
            "Segundo o prefeito da cidade, Benoît Payan, seis feridos foram internados e cinco deles estão em estado grave.",
            "Ainda segundo bombeiros, dois prédios vizinhos foram atingidos por destroços e um deles já ruiu. Os moradores de um terceiro imóvel que fica na mesma rua receberam ordem para deixar o local.",
            "Até o momento, a causa do desabamento não foi identificada. Mas moradores da região relataram que houve uma explosão antes do prédio cair.",
            "O edifício no centro do incidente fica no número 15 da rua Tivoli, no 5° distrito de Marselha, uma área com cafés, restaurantes e imóveis de habitação. Segundo autoridades locais, o prédio tinha sido reformado recentemente e não apresentava risco por insalubridade, nem o vizinho, que também desabou, no número 17 da mesma rua.",
            "Em 11 de janeiro de 1981, oito pessoas morreram e 16 ficaram feridas no desmoronamento de um edifício no bairro de Canet, habitado por famílias de baixa renda. Outras cinco pessoas morreram em 1985, em uma explosão acidental ocorrida em um prédio próximo ao Boulevard do Prado. Em 20 de julho de 1996, uma explosão de gás derrubou um prédio de sete andares próximo à estação de trem de Saint-Charles, deixando quatro mortos e 26 feridos.",
            "Não foi um, nem dois, nem três. Três mulheres e três adolescentes foram flagradas pelas câmeras de segurança do Guanabara, da Tijuca, na Zona Norte do Rio, na noite da terça-feira (4), tentando sair do local com 56 ovos de Páscoa e três pares de chinelo.",
            "Elas colocaram os itens em bolsas de mercado e tentaram sair sem pagar, mas foram abordadas e armaram confusão com os seguranças da loja. A situação rendeu vídeos que circularam pelas redes sociais (veja no vídeo acima), e um prejuízo de R$ 3.476,10.",
            "O caso foi parar na polícia. A contagem dos itens foi feita na 19ª DP (Tijuca), que registrou o caso, e ocupou todo o balcão da delegacia. As mulheres foram presas e as menores, apreendidas.",
            "A rede de supermercados Guanabara foi procurada pelo g1, mas não se manifestou sobre o caso até a publicação da reportagem.",
            "Já Luara Aguiar Martins de Melo, de 18 Anos, Larissa Yanka Rodrigues da Silva, de 20, e Thaynara Miranda da Silva, de 21 Anos, passaram por audiência de custódia na quinta-feira (6), e tiveram a prisão em flagrante convertida para preventiva.",
            "A presa Thaynara Miranda da Silva foi fichada no dia 5 de abril, dia em que completava 21 anos. Durante a audiência de custódia, ela ainda apresentou um comprovante de matrícula em curso superior de Direito, que havia acabado de ingressar – matriculou-se no dia 30 de março, pagou no dia 3 de abril e foi presa no dia 4.",
            "Sanseverino atuava na Terceira Turma do Tribunal e na Segunda Seção do STJ - colegiados especializados em direito privado e, também, como ministro substituto do TSE.",
            "Morreu, neste sábado (8), o ministro Paulo de Tarso Sanseverino, do Superior Tribunal de Justiça (STJ) e do Tribunal Superior Eleitoral (TSE), aos 63 anos.",
            "Nascido em Porto Alegre em junho de 1959, o ministro se tornou bacharel em Direito pela Pontifícia Universidade Católica do Rio Grande do Sul em 1983.",
            "Na carreira jurídica, Sanseverino foi promotor de Justiça entre 1984 e 1986 - aprovado em primeiro lugar no concurso para o Ministério Público do estado do Rio Grande do Sul. Foi juiz na Justiça do estado entre 1986 e 1999 e também atuou como juiz eleitoral entre 1998 e 1999. Ainda na Justiça estadual, atuou como desembargador entre os anos de 1999 e 2010.",
            "Em agosto 2010, Sanseverino nomeado para o Superior Tribunal de Justiça. Atualmente, atuava na Terceira Turma do Tribunal e na Segunda Seção do STJ - colegiados especializados em direito privado. Também atuou na Corte Especial, que reúne os ministros mais antigos do tribunal.",
            "Ele estava internado no Hospital Moinhos de Vento, em Porto Alegre, devido a um câncer. O velório será neste domingo (9), a partir das 10h, na capela do Cemitério São José, no Crematório Metropolitano de Porto Alegre (avenida Oscar Pereira, 584, bairro Azenha). Na segunda-feira (10), o velório prosseguirá a partir das 7h30, no auditório do Crematório Metropolitano. A cerimônia de despedida está prevista para as 15h.",
            "Silvinei Vasques, ex-chefe da PRF, foi o braço operacional do maior escândalo das eleições de 2022: a tentativa de tumultuar o pleito, fazendo blitz contra carros e ônibus que ostentavam adesivos da campanha de Lula no dia da votação. Corregedor Wendel Matos era obrigado a comunicar à CGU possíveis infrações do superior hierárquico.",
            "Ex-corregedor da Polícia Rodoviária Federal, Wendel Benevides Matos escondeu da Controladoria-Geral da União (CGU) 23 denúncias envolvendo seu chefe, o ex-diretor-geral Silvinei Vasques. Por se tratar de um superior hierárquico, Wendel era obrigado a comunicar à CGU sobre as possíveis infrações de Silvinei. No entanto, não foi encontrado nenhum registro no sistema correcional da controladoria.",
            "Nomeado no governo Bolsonaro, Wendel tinha mandato até novembro, mas foi exonerado nesta semana a pedido da atual direção da PRF. Silvinei, o chefe que teria sido protegido pelo corregedor, foi o braço operacional do maior escândalo das eleições de 2022: a tentativa de tumultuar o pleito, fazendo blitz contra carros e ônibus que ostentavam adesivos da campanha de Lula no dia da votação do segundo turno. As ações se concentraram no Nordeste, onde o petista tem o maior número de eleitores.",
            "A exoneração do corregedor foi pedida pela atual direção da PRF por 'indícios de distorções técnicas, parcialidade, interferência e uso não isonômico das ferramentas de correição pelo atual Corregedor Geral'. Ficou constatado que Wendel usava dois pesos e duas medidas ao investigar manifestações político-partidárias de policiais.",
            "Quando os servidores declaravam apoio a candidatos de esquerda, os processos disciplinares eram instaurados rapidamente. O mesmo não acontecia quando as manifestações em redes sociais envolviam Bolsonaro ou seus apoiadores. O próprio Silvinei Vasques fez declarações públicas a favor do candidato do PL.",
            "Na época, o então corregedor afirmou: “Observamos que nenhuma ordem foi dada no sentido de que servidores não deixassem de cumprir o seu papel”. Até agora, a Corregedoria-Geral da União não sabe de onde ele tirou essa conclusão, já que não houve qualquer procedimento de apuração.",
            "Vítimas foram socorridas para hospitais da região. Segundo a polícia, nenhuma delas corre risco de vida. Crime aconteceu na noite de quinta-feira (6), no Centro de Américo Brasiliense (SP).",
            "Um homem procurou atendimento médico no Hospital Municipal José Nigro Neto, em Américo Brasiliense (SP) e, depois, esfaqueou a equipe médica e pacientes que estavam no local, na noite de quinta-feira (6). Ao todo, sete pessoas ficaram feridas.",
            "A princípio, ele é uma pessoa que usa drogas na cidade. Ele causa alguns problemas e veio até o pronto atendimento nervoso. Foram tentar medicar, ele sacou a faca', afirmou o major Alan Esteves Fernandes Gouvêa.",
            "Ainda de acordo com a PM, o agressor manteve uma pessoa refém. A viatura da polícia estava perto do local e conseguiu controlar rapidamente a situação.",
            "'Ele não soltava, estava com a faca a todo tempo tentando esfaquear. E em um determinado momento a pessoa conseguiu se afastar dele, e o policial efetuou os disparos.'",
            "Assim como as vítimas, o agressor chegou a ser socorrido, mas não resistiu aos ferimentos e morreu. De acordo com a PM, nenhuma das pessoas feridas corre risco de vida. O caso foi registrado no Plantão Policial de Araraquara."
        ]
    }

    /**
     * return a pool to generate fake text
     * @returns {Array}
     */
    static textPool() {
        return `O presente trabalho apresenta os impactos sociais e consequências do alastramento denotícias falsas, as chamadas fake news. Com o objetivo de buscar soluções para evitar sua propagação, o estudo propõe verificar como a avaliação de fontes de informação pode evitar a disseminação de fake news. A metodologia escolhida para a realização do trabalho foi a de natureza qualitativa. Trata-se de uma pesquisa exploratória que utiliza-se de observação direta e pesquisas documental e bibliográfica. Foi definido o conceito de fake news e seus impactos na sociedade expostos através de variados exemplos, tanto no âmbito político como no de saúde, além das medidas tomadas por diferentes entidades para evitá-las. Realizou-se uma análise de diversos trabalhos, dos quais foram selecionados cinco critérios de avaliação de informação que mais se adequaram ao objetivo do trabalho. Cinco canais de informação foram analisados de acordo com os critérios escolhidos pelo trabalho, apresentando resultados em sua maioria positivos, e concluiu-se que os critérios de avaliação podem auxiliar a identificação de qualidade de informação, mas faz-se necessário uma melhor educação dos usuários. A internet tem se mostrado uma ferramenta indispensável na vida do ser humano. A evolução tecnológica permitiu que o uso da rede se tornasse natural, tão parte do dia a dia como a televisão e o jornal costumavam ser antes da era digital. Além de possibilitar maior velocidade de comunicação através de mensagens imediatas, tornou-se um veículo de informação em tempo real. Nos dias atuais, é necessário apenas que uma pessoa utilize o navegador de seu smartphone para que tenha acesso às notícias do dia. A despeito de o livre acesso à informação ser algo positivo, ainda há inconvenientes encontrados nesse cenário. A facilidade em produzir e compartilhar qualquer conteúdo online possibilita a propagação de inverdades, que por sua vez podem espalhar-se e afetar aqueles que receberam uma informação falsa. Em vista disso, esse trabalho pretende analisar as informações propagadas incorretamente, conhecidas popularmente como “fake news”, e seu impacto na sociedade. Este estudo torna-se relevante a partir do momento que se considera o papel do bibliotecário na disseminação da informação. De acordo com a Classificação Brasileira de Ocupações (CBO), uma das atividades realizadas pelos profissionais da informação é disseminar informação com o objetivo de facilitar o acesso e geração do conhecimento. Por conseguinte, o profissional bibliotecário pode ter um papel significativo na redução do alastramento de fake news. A partir destas considerações, visamos responder a seguinte pergunta: como a avaliação de fontes de informação pode desacelerar o alastramento de fake news? Partindo-se da hipótese de que a avaliação de fontes de informação pode evitar que os consumidores de informação sejam influenciados por notícias falsas, este trabalho objetiva analisar canais informacionais para avaliar a confiabilidade das fontes disponibilizadas, e traz como objetivos específicos averiguar o significado de fake news e seus impactos na sociedade, conceituar uma informação de qualidade e determinar critérios que auxiliem em sua identificação. Para alcançar o objetivo geral, a metodologia adotada será de abordagem qualitativa. Quanto aos objetivos, exploratória, e quanto aos procedimentos, bibliográfica e de estudo de caso. As ferramentas de pesquisa para o estudo de caso serão: observação direta e pesquisa documental. Andrade (20181) acrescenta que o turbilhão de informações e a disseminação rápida de informação faz com que surjam diversas versões sobre os eventos, dessa forma facilitando a criação de pós-verdades por parte de pessoas mal intencionadas. De acordo com a autora, a pós-verdade se refere ao momento em que a verdade perde sua relevância, e acrescenta que a presença da pós-verdade é o que permite que notícias falsas sejam divulgadas amplamente nas mídias digitais. Frias (2018, p. 42) ressalta que a novidade não está nas fake news em si, mas sim na aparição de um instrumento capaz de reproduzi-las e disseminá-las com amplitude e velocidade inauditas. Delavald (2018) atribui a popularização das fake news ao índice medíocre de leitura de grande parte dos usuários da rede. Para o autor, a quantidade de informações dispostas na internet faz com que os usuários considerem um grande esforço procurar a veracidade das fontes que consultam. De acordo com a Pesquisa Nacional por Amostra de Domicílios Contínua, realizada pelo IBGE (BRASIL, 2018) o celular foi utilizado para o acesso à internet em 97,2% dos domicílios, sendo o equipamento de acesso mais usado nos domicílios. A pesquisa, realizada em 2016, salienta que o celular foi o principal equipamento usado para acessar a Internet; apenas 2,3% das residências com Internet utilizavam apenas o computador para esse fim, embora estivesse presente em mais da metade (57,8%) desses domicílios. Tendo esses dados em vista, podemos observar o aumento do uso dos celulares por parte da população brasileira, e dessa forma, sua influência sobre seus usuários é significativa. Com a praticidade do smartphone, o acesso às redes sociais e notícias é facilitada- e com isso, a propagação das fake news. Muitas das notícias falsas eram provocações abertas aos candidatos das eleições de 2016. As fake news, se usadas de forma correta, podem atingir determinado grupo de eleitores, fazendo com que mudem de opinião sobre em quem votariam, uma baixa forma de manipulação que não afeta apenas os americanos. O Buzzfeed Brasil reuniu em um post as dez notícias falsas mais compartilhadas a respeito da Lava Jato2 ,quase sempre envolvendo umpartido político ou um possível candidato à presidência. O site, que é conhecido por seus testes inusitados, chegou a criar um teste intitulado “Se você acertar menos de 6 neste teste, as fake news estão te confundindo”, utilizando uma forma descontraída de chamar a atenção dos seus leitores para os perigos das fake news. Outra notícia falsa que tornou-se popular no país foi a implementação do “kit gay”, um material que seria distribuído nas escolas de forma a incentivar a homossexualidade e promiscuidade em crianças e adolescentes. Na realidade, segundo Soares (2015), trata-se do projeto Brasil sem Homofobia, criado pelo congresso em 2004 com o objetivo de combater a violência e o preconceito contra a população LGBT. De acordo com o autor, uma faceta desse projeto enfatizaria a formação de educadores para tratar questões relacionadas ao gênero e à sexualidade. O texto destaca que o termo kit gay foi usado de forma pejorativa pelos membros conservadores do Congresso Nacional. Essa notícia tem percorrido as redes desde 2011, quando foi vetada pela presidente Dilma Rousseff, mas ganhou destaque novamente nas eleições de 2018, ao ser usada pelo candidato Bolsonaro, do PSL, como um argumento para desacreditar seu adversário Fernando Haddad (PT), a quem atribuiu a responsabilidade pela elaboração do projeto em uma entrevista à Jovem Pan (2018). Apesar de boa parte do material ter sido disponibilizado online e estar comprovado que não há nada nele que incentive relações sexuais entre crianças, ainda é criticado e utilizado como um argumento para atrair votos de eleitores mais conservadores, público alvo de Bolsonaro. Apesar do que discorremos anteriormente, as fake news não influenciam somente o âmbito da política. De acordo com a matéria realizada por Augusto (2018), das nove vacinas prioritárias do calendário infantil, nenhuma atingiu a meta de 95% de imunização no ano passado, não passando dos 70%. Preocupados com o alastramento das fake news e seus impactos na saúde pública, o Ministério da Saúde lançou em 2018 o programa Saúde Sem Fake News, no qual foi disponibilizado um número de WhatsApp para a população. O pronunciamento destaca que o programa “não será um SAC ou tira dúvidas dos usuários, mas um espaço exclusivo para receber informações virais, que serão apuradas pelas áreas técnicas e respondidas oficialmente se são verdade ou mentira”. De acordo com Naísa (2018), o programa recebeu mais de 2.151 mensagens desde que foi lançado. As perguntas mais recorrentes são referentes a proibição da vacinação contra o HPV pelo Ministério Público Federal, um câncer de olho causado pelo uso de smartphones, vírus HIV sendo injetado dentro de frutas e a presença de uma bactéria no feijão que pode ser combatida com vinagre, todas confirmadas como falsas pela autora. cinemas, repercutiu rapidamente e espalhou-se em diferentes meios informacionais, causando revolta por parte dos fãs da franquia. De acordo com Mennitti (2018), o site afirma que “os diálogos contratuais travados entre a Warner e os representantes de Henry Cavill, da companhia de agenciamento WME, não renderam bons frutos”. Apesar dessa declaração dificilmente contar como uma afirmação oficial da companhia, muitos sites e blogs propagaram essa notícia como se fosse verdadeira, mesmo que nem o ator e nem a Warner tenham se pronunciado a respeito. A notícia foi desmentida poucas horas depois. É inegável a influência das redes sociais como Twitter, Facebook e WhatsApp no alastramento de fake news. Por tratar-se de plataformas nas quais é possível criar conteúdo, que pode ser facilmente repassado e compartilhado com capacidade de alcance internacional, não é surpreendente que sejam escolhidas como veículos de disseminação de notícias falsas Apesar de seus esforços para impedir a circulação de fake news na plataforma, o número de fake news compartilhadas através do Facebook ainda é comum. Por essa razão, o Facebook anunciou a criação do botão de contexto, ferramenta criada para auxiliar a identificação de fontes confiáveis. Tendo início como um teste nos EUA no ano 2017, o recurso foi disponibilizado em 2018 para os países Brasil, Colômbia e México, e já pode ser utilizado por aqueles que atualizaram o aplicativo. Agora sempre que um veículo de notícias compartilhar um link, haverá um “i” sobre ele, Ao clicar no ícone veremos informações sobre o site, entre elas uma descrição, mais links compartilhados pelo veículo e um mapa informando em quais locais aquele link foi compartilhado. O foco, dizem Hughes, Smith e Leavitt (2018), é disponibilizar as informações e deixar que os leitores decidam por si mesmos no que devem confiar. “Continuaremos a buscar formas de melhorar esta experiência e ajudar as pessoas a terem mais contexto sobre as notícias que veem no Facebook”, afirmaram os autores em comunicado oficial da plataforma. Conforme Demartini (2018), a empresa Twitter anunciou mudanças nas regras de forma a se manter atentos à disseminação de fake news. Agora a empresa passa a observar o tipo de postagem em si, de acordo com uma série de padrões de manipulação política, além da utilização de bios copiadas de outros perfis, imagens falsas ou retiradas de bancos de imagens e informações inconsistentes entre a localidade apontada na conta e o local de realização dos posts. A empresa também afirma ter incrementado seu algoritmo de moderação para perceber quando uma conta pertence a um grupo ou entidade. Caso uma delas seja responsável pela violação das regras, é possível que as outras também sejam banidas. O WhatsApp, aplicativo visto como maior culpado pelo alastramento de fake news, anunciou medidas para tentar conter a disseminação de notícias falsas, identificando claramente as mensagens que são encaminhadas e limitando o número de destinatários para repassar mensagens a 20 grupos por vez - e a cinco na Índia (Martínez, 2018). Segundo Dixit e Mac (2018), a preocupação maior com a Índia justifica-se por ser usado por mais de 200 de milhões pessoas na Índia, seu maior mercado. Ele se tornou parte indissociável da cultura e da estrutura social do país, afirmam os autores, sendo utilizados por todas as gerações. No entanto, o uso do WhatsApp tem causado um alastramento desenfreado de notícias falsas, chegando a causar mortes no país. Desde maio, houve ao menos 16 linchamentos na Índia, resultando em 29 mortes. Segundo funcionários públicos, os linchamentos foram incitados por informações falsas. Os autores explicam uma situação de tragédia ocorrida no vilarejo de Rainpad. Vídeos virais encaminhados por fontes desconhecidas sobre supostos sequestradores de crianças circulavam por meses, causando revolta na população. Os vídeos ainda encerram com um pedido de compartilhamento, utilizando-se de chantagem emocional para convencer os usuários do aplicativo. De acordo com os autores, cinco homens membros de uma tribo nômade do nordeste de Maharashtra, o Estado indiano que compreende Rainpada, visitaram o vilarejo para participar no mercado semanal. Ao presenciar um dos visitantes oferecendo biscoitos para uma criança, um estudante, apavorado com as notícias que circulavam no WhatsApp, disparou um alarme. Apesar de não ter sido claro para os investigadores do caso como a situação evoluiu para a violência, o linchamento resultou na morte dos cinco visitantes. De acordo com Martínez (2018), a Índia não foi o único local a ter linchamentos causados por correntes de notícias através do WhatsApp. Uma história suscitada em algum lugar desconhecido e propagada pelo aplicativo em Acatlán, no México, alertava também para possíveis sequestradores de crianças envolvidos em tráfico de órgãos. Um rapaz e seu tio tinham ido à cidade para visitar a família, e foram abordados por uma multidão. Por conta da abordagem dos moradores, ambos foram levados à delegacia, onde uma multidão se reuniu em protesto. Ao constatarem que os possíveis criminosos seriam soltos, a multidão se mobilizou para linchá-los. A situação acabou em tragédia; os rapazes foram linchados e em seguida carbonizados pela população. Trazendo a situação para o Brasil, uma jornalista da BBC passou sete dias acompanhando grupos de política no aplicativo WhatsApp com a ajuda de um sistema desenvolvido por pesquisadores brasileiros. Chamado Monitor de WhatsApp, o sistema acompanhou 272 grupos públicos de WhatsApp por meio de celulares destacados só para isso e mostra as imagens, links, vídeos e textos compartilhados nos grupos. Gragnani (2018) esclarece que seu objetivo era “entender a lógica de distribuição do conteúdo político que chega a milhões de pessoas diariamente pelo WhatsApp, principalmente no período eleitoral”. A autora acrescenta que durante esse período de uma semana presenciou muita desinformação, incluindo imagens fora de contexto, fotos manipuladas, pesquisas errôneas, além de ataques à imprensa tradicional e fomentação de ódio a minorias. A jornalista salienta que quase todas informações falsas que encontrou durante os sete dias já haviam sido checadas pela imprensa brasileira, sendo necessário não mais que uma pesquisa rápida no Google para identificá-las.`
    }

    /**
     * return a pool to generate fake post
     * @returns {Array}
     */
    static fakePost() {
        return ["Você é muito mais do que a opinião alheia. Você é uma pessoa incrível e merece ser feliz.",
            "Só preciso de uma viagem para recomeçar a minha vida!",
            "Acorde pra vida, você não precisa ficar sofrendo por quem não merece.",
            "E tudo fica mais lindo quando você chega e aquece a minha alma, me abraça e me conforta com os seus beijos.",
            "Se a sua paz está em jogo, pare e repense as suas escolhas. Se custa a sua paz, custa caro demais.",
            "Seu maior compromisso é com você mesma, com o seu crescimento e suas realizações.",
            "Não dá pra ter paz e equilíbrio emocional se você não se permite evoluir.",
            "Viver tentando agradar as pessoas ao seu redor só irá gerar uma vida de frustrações.",
            "Cultive a sua autoestima e tenha mais amor próprio. Seja você mesma e conquiste o mundo!",
            "Uma vida sem desafios, é uma vida sem evolução. Arrisque mais, liberte-se dos medos!",
            "Olhe pra você com mais amor, o seu corpo te protege, te sustenta, é a casa da sua alma.",
            "Se apaixone por você, compartilhe suas experiências, se enxergue com bons olhos, sorria.",
            "E com tantas coisas que vem acontecendo, hoje eu só prezo pela minha felicidade.",
            "Seja uma mulher que apoia, admira e fortalece outras mulheres. Juntas nós vamos além!",
            "Então, vem comigo! Eu prometo que vamos construir uma linda história de amor.",
            "Autocuidado é muito mais que um dia de relaxamento. Cuide da sua alma e preserve a sua felicidade.",
            "A vida é um eterno ir e vir. Tudo muda o tempo todo, e precisamos evoluir.",
            "Não é porque não saiu como esperado que você deve desistir das suas metas. Levante a cabeça.",
            "Deixe que a vida siga o seu fluxo! Honre a sua história, agradeça, evolua e se permita ser feliz.",
            "Às vezes, fico pensando em ti, e me perguntando como é que foi que chegamos ao fim.",
            "Deixe o passado para trás, permita que a sua vida tenha um novo espaço para momentos felizes.",
            "Agradeço a Deus pela alegria diária que tenho tido em minha vida!",
            "Às vezes, tudo que a gente precisa é um bom vinho e uma boa companhia.",
            "Tudo que eu queria era um abraço apertado, um beijo molhado.",
            "Tem amigos que a gente deseja nunca mais abandonar!",
            "Você já se olhou no espelho hoje e agradeceu por mais um dia?",
            "Chega de reclamar da vida, aprenda a viver mesmo com incertezas.",
            "“Uma vez que você se sinta evitado por alguém, nunca mais o perturbe”. (Carol Dutra)",
            "“Não diminua quem você é para caber no mundo de outro alguém”. (Drica Serra)",
            "“Amar alguém é viver o exercício constante de não querer fazer do outro o que a gente gostaria que ele fosse”. (Padre Fábio de Melo)",
            "“A experiência de amar e ser amado é, acima de tudo, a experiência de respeito”. (Padre Fábio de Melo)",
            "“Procuro semear otimismo e plantar sementes de paz e justiça. Digo o que penso, com esperança. Penso no que faço, com fé. Faço o que devo fazer, com amor. Eu me esforço para ser cada dia melhor, pois bondade também se aprende”. (Cora Coralina)",
            "“Quando a alma está feliz, a prosperidade cresce, a saúde melhora, as amizades aumentam, enfim, o mundo fica de bem com você”. (Gandhi)",
            "“A vida é uma peça de teatro que não permite ensaios. Por isso, cante, chore, dance, ria e viva intensamente, antes que a cortina se feche e a peça termine sem aplausos”. (Charlie Chaplin)",
            "“Não existe falta de tempo, existe falta de interesse. Porque quando a gente quer mesmo, a madrugada vira dia. Quarta-feira vira sábado e um momento vira oportunidade”. (Pedro Bial)",
            "“Escolha sempre pessoas melhores que você. Sempre escolha pessoas que o desafiem e sejam mais inteligentes que você. Seja sempre um aprendiz”. (Sandra Bullock)",
            "“Só porque você não compartilha nas redes sociais, não significa que você não faça coisas grandiosas. Viva e mantenha-se em sigilo. Privacidade é tudo”. (Denzel Washington)",
            "“Se você não pode explicar algo de forma simples, então você não entendeu muito bem o que tem a dizer”. (Albert Einstein)",
            "“Tenha coragem de seguir o que seu coração e sua intuição dizem. Eles já sabem o que você realmente deseja”. (Steve Jobs)",
            "“Loucura é querer resultados diferentes fazendo tudo exatamente igual”. (Albert Einstein)",
            "“Se você consegue imaginar, você consegue fazer”. (Walt Disney)",
            "“A paciência é um elemento fundamental do sucesso”. (Bill Gates)",
            "“Eu gosto do impossível porque lá a concorrência é menor”. (Walt Disney)",
            "“Um objetivo é um sonho com cronograma”. (Napoleon Hill)",
            "“Daqui 20 anos, você estará mais arrependido pelas coisas que não fez do que pelas que fez”. (Mark Twain)",
            "“Acredito bastante na sorte. E notei que quanto mais eu trabalho duro, mais sorte eu tenho”. (Thomas Jefferson)",
            "“Cada segundo é tempo para mudar tudo para sempre”. (Charles Chaplin)",
            "“Não há nada mais precioso que dar risada”. (Frida Kahlo)",
            "“Um campeão é alguém que se levanta apesar de não ser capaz”. (Jack Dempsey)",
            "“Quando tudo está perdido, sempre existe um caminho”. (Legião Urbana)",
            "“O essencial é invisível aos olhos”. (O Pequeno Príncipe)",
            "“Acreditando apaixonadamente em uma coisa que ainda não existe, nós a criamos”. (Franz Kafka)",
            "“A vida é curta demais para ser gasta com animosidades, só pensando nos momentos ruins”. (Jane Eyre)",
            "“Entregue-se à sua imaginação para voos mais arrojados”. (Jane Austen)",
            "“Tu te tornas eternamente responsável por aquilo que cativas”. (O Pequeno Príncipe)",
            "“Quando tiver que escolher entre estar certo ou ser gentil, escolha ser gentil”. (Extraordinário)",
            "“Mais esperança nos meus passos do que tristeza nos meus ombros”. (Cora Coralina)"]
    }

}

module.exports = SocialNetworkHelpers;