'use strict'

class SportsHelpers {

    /**
    * This method return a array wwith a brazilian Champions
    * @returns {Array<string>}
    */
    static randomChampionShip() {
        return [
            "Libertadores",
            "Copa do Brasil",
            "Copa Sul-Americana",
            "Brasileirão Feminino",
            "Paulistão",
            "Carioca",
            "Mineiro",
            "Gaúcho",
            "Pernambucano",
            "Copa do Nordeste",
            "Brasileirão Sub-20",
            "Copa do Brasil Sub-17",
            "Brasileirão",
            "Brasileirão Série B",
            "Brasileirão Série C",
            "Brasileirão Série D"
        ]
    }

    /**
     * This method return a array wwith a brazilian teams
     * @returns {Array<string>}
     */
    static randomTeam() {
        return [
            "ABC ",
            "Altos",
            "América-MG ",
            "América-PE",
            "América-RN",
            "Anapolina",
            "Aparecidense",
            "Ariquemes",
            "ASA",
            "Athletico Paranaense",
            "Atlético Acreano",
            "Atlético Goianiense",
            "Atlético Mineiro",
            "Atlético Roraima",
            "Atlético Tubarão",
            "Avaí",
            "Avenida",
            "Bahia",
            "Bahia de Feira",
            "Barcelona-RO",
            "Boa",
            "Boavista",
            "Botafogo",
            "Botafogo-PB",
            "Botafogo-SP",
            "Bragantino",
            "Bragantino-PA",
            "Brasil",
            "Brasiliense",
            "Brusque",
            "Caldense",
            "Campinense",
            "Caxias",
            "Ceará",
            "Central",
            "Chapecoense",
            "Cianorte",
            "Confiança",
            "Corinthians",
            "Coritiba",
            "Corumbaense",
            "Coruripe",
            "CRB",
            "Criciúma",
            "Cruzeiro",
            "CSA",
            "Cuiabá",
            "Fast Club",
            "Ferroviária",
            "Ferroviário",
            "Figueirense",
            "Flamengo",
            "Floresta",
            "Fluminense",
            "Fluminense de Feira",
            "Fortaleza",
            "Foz do Iguaçu",
            "Galvez",
            "Gaúcho",
            "Globo",
            "Goiás",
            "Grêmio",
            "Guarani",
            "Hercílio Luz",
            "Imperatriz",
            "Internacional",
            "Interporto",
            "Iporá",
            "Itabaiana",
            "Itaboraí",
            "Ituano ",
            "Jacuipense",
            "Joinville",
            "Juazeirense",
            "Juventude",
            "Londrina",
            "Luverdense",
            "Manaus",
            "Maranhão",
            "Maringá",
            "Moto Club",
            "Náutico",
            "Novorizontino",
            "Oeste",
            "Operário",
            "Operário-MS",
            "Palmas",
            "Palmeiras",
            "Paraná",
            "Patrocinense",
            "Paysandu",
            "Ponte Preta",
            "Portuguesa-RJ",
            "Remo",
            "Rio Branco",
            "River-PI",
            "Salgueiro",
            "Sampaio Corrêa",
            "Santa Cruz",
            "Santa Cruz de Natal",
            "Santos",
            "Santos-AP",
            "São Bento",
            "São Caetano",
            "São José",
            "São Paulo",
            "São Raimundo-AM",
            "São Raimundo-PA",
            "Sergipe",
            "Serra",
            "Serrano",
            "Sinop",
            "Sobradinho",
            "Sport",
            "Tombense",
            "Treze",
            "Tupi",
            "União Rondonópolis",
            "Uniclinic",
            "URT",
            "Vasco da Gama",
            "Vila Nova",
            "Vitória",
            "Vitória das Tabocas",
            "Vitória-ES",
            "Volta Redonda",
            "Ypiranga-AP",
            "Ypiranga-RS",
        ]
    }

    /**
     * This method return a string array with a Braziliam Stadium
     * @returns {Array<string>}
     */
    static stadium() {
        return [
            "Maracanã, Rio de Janeiro, Rio de Janeiro RJ, Gov. Estadual, Capacidade: 78.838",
            "Mané Garrincha, Brasília, Distrito Federal (Brasil) DF, Gov. Distrital, 72.788",
            "Morumbi, São Paulo, São Paulo SP, Privado,Capacidade: 66.975",
            "astelão, Fortaleza, Ceará CE, Gov. Estadual, Capacidade: 63.903",
            "ineirão, Belo Horizonte, Minas Gerais MG, 61.846",
            "rruda, Recife, Pernambuco PE, Privado,Capacidade: 60.044",
            "rena do Grêmio, Porto Alegre, Rio Grande do Sul RS, 55.662",
            "angueirão, Belém, Pará PA, Gov. Estadual, Capacidade: 53.645",
            "arque do Sabiá, Uberlândia, Minas Gerais MG, Gov. Municipal, Capacidade: 53.350",
            "Beira-Rio, Porto Alegre, Rio Grande do Sul RS, Privado,Capacidade: 50.942",
            "Arena Fonte Nova, Salvador, Bahia BA, Gov. Estadual, Capacidade: 50.025",
            "Neo Química Arena, São Paulo, São Paulo SP, Privado,Capacidade: 47.605",
            "Nilton Santos, Rio de Janeiro, Rio de Janeiro RJ, Gov. Municipal, Capacidade: 46.831",
            "Arena de Pernambuco, São Lourenço da Mata, Pernambuco PE, Gov. Estadual, Capacidade: 46.154",
            "Arena MRV, Belo Horizonte, Minas Gerais MG, Privado,Capacidade: 46.000",
            "Prudentão, Presidente Prudente, São Paulo SP, Gov. Municipal, Capacidade: 45.954",
            "Albertão, Teresina, Piauí PI, Gov. Estadual, Capacidade: 44.200",
            "Morenão, Campo Grande, Mato Grosso do Sul MS, Gov. Federal, 44.200",
            "Arena Pantanal, Cuiabá, Mato Grosso MT, Gov. Estadual, Capacidade: 44.097",
            "Arena da Amazônia, Manaus, Amazonas AM, 44.000",
            "Allianz Parque, São Paulo, São Paulo SP, Privado,Capacidade: 43.713",
            "Arena da Baixada, Curitiba, Paraná PR, 42.372",
            "Serra Dourada, Goiânia, Goiás GO, Gov. Estadual, Capacidade: 42.000",
            "Couto Pereira, Curitiba, Paraná PR, Privado,Capacidade: 40.502",
            "Castelão, São Luís, Maranhão MA, Gov. Estadual, Capacidade: 40.149",
            "Barradão, Salvador, Bahia BA, Privado,Capacidade: 35.000",
            "Pinheirão, Curitiba, Paraná PR",
            "Olímpico da USP, São Paulo, São Paulo SP",
            "Ilha do Retiro, Recife, Pernambuco PE, 32.983",
            "Teixeirão, São José do Rio Preto, São Paulo SP, 32.936",
            "Pituaçu, Salvador, Bahia BA, Gov. Estadual, Capacidade: 32.157",
            "Arena das Dunas, Natal, Rio Grande do Norte RN, Privado,Capacidade: 32.050",
            "Helenão, Juiz de Fora, Minas Gerais MG, Gov. Municipal, Capacidade: 31.863",
            "Arena Barueri, Barueri, São Paulo SP, 31.452",
            "Estádio do Café, Londrina, Paraná PR, 30.000",
            "Douradão, Dourados, Mato Grosso do Sul MS, Gov. Estadual",
            "Santa Cruz, Ribeirão Preto, São Paulo SP, Privado,Capacidade: 29.292",
            "Brinco de Ouro, Campinas, 29.130",
            "Boca do Jacaré, Taguatinga, Distrito Federal (Brasil) DF, Gov. Distrital, 27.000",
            "Irmão Gino Maria Rossi, Pouso Alegre, Minas Gerais MG, Gov. Municipal, Capacidade: 26.000",
            "Pacaembu, São Paulo, São Paulo SP",
            "Almeidão, João Pessoa, Paraíba PB, Gov. Estadual, Capacidade: 25.770",
            "Amigão, Campina Grande",
            "Regional Arnaldo Busatto, Cascavel, Paraná PR, Gov. Municipal, Capacidade: 25.000",
            "São Januário, Rio de Janeiro, Rio de Janeiro RJ, Privado,Capacidade: 24.584",
            "Major Levy Sobrinho, Limeira, São Paulo SP, Gov. Municipal, Capacidade: 23.475",
            "Independência, Belo Horizonte, Minas Gerais MG, Privado,Capacidade: 23.018",
            "Aflitos, Recife, Pernambuco PE, 22.856",
            "Ipatingão, Ipatinga, Minas Gerais MG, Gov. Municipal, Capacidade: 22.500",
            "Canindé, São Paulo, São Paulo SP, Privado,Capacidade: 22.375",
            "Centenário, Caxias do Sul, Rio Grande do Sul RS, 22.132",
            "Colosso da Lagoa, Erechim, 22.000",
            "Vila Belmiro, Santos, São Paulo SP, 21.732",
            "Arena da Fonte Luminosa, Araraquara, Gov. Municipal, Capacidade: 21.441",
            "Kleber Andrade, Cariacica, Espírito Santo (estado) ES, Gov. Estadual, Capacidade: 21.000",
            "Bezerrão, Gama, Distrito Federal (Brasil) DF, Gov. Distrital, 20.300",
            "Presidente Vargas, Fortaleza, Ceará CE, Gov. Municipal, Capacidade: 20.268",
            "Raulino de Oliveira, Volta Redonda, Rio de Janeiro RJ, 20.255",
            "Arena Condá, Chapecó, Santa Catarina SC, 20.200",
            "Arena Joinville, Joinville, 20.160",
            "Arena do Jacaré, Sete Lagoas, Minas Gerais MG, Privado,Capacidade: 20.020",
            "Arena Acreana, Rio Branco, Acre AC, Gov. Estadual, Capacidade: 20.000",
            "Willie Davids, Maringá, Paraná PR, Gov. Municipal",
            "Alfredo Jaconi, Caxias do Sul, Rio Grande do Sul RS, Privado,Capacidade: 19.924",
            "Heriberto Hülse, Criciúma, Santa Catarina SC, 19.900",
            "Vail Chaves, Mogi Mirim, São Paulo SP",
            "Moisés Lucarelli, Campinas, 19.728",
            "Orlando Scarpelli, Florianópolis, Santa Catarina SC, 19.584",
            "Lacerdão, Caruaru, Pernambuco PE, 19.478",
            "Arena Capivari, Capivari, São Paulo SP, Gov. Municipal, Capacidade: 19.000",
            "Alfredão, Bauru, Privado,Capacidade: 18.886",
            "Novelli Júnior, Itu, Gov. Municipal, Capacidade: 18.560",
            "Parque São Jorge, São Paulo, Privado,Capacidade: 18.500",
            "Palma Travassos, Ribeirão Preto, 18.277",
            "Barão de Serra Negra, Piracicaba, Gov. Municipal, Capacidade: 18.000",
            "Ítalo del Cima, Rio de Janeiro, Rio de Janeiro RJ, Privado",
            "Luthero Lopes, Rondonópolis, Mato Grosso MT, Gov. Municipal",
            "Ressacada, Florianópolis, Santa Catarina SC, Privado,Capacidade: 17.826",
            "Arena Romeirão, Juazeiro do Norte, Ceará CE, Gov. Municipal, Capacidade: 17.230",
            "Felipão, Paranavaí, Paraná PR, 17.147",
            "Vila Capanema, Curitiba, Privado,Capacidade: 17.140",
            "Nabi Abi Chedid, Bragança Paulista, São Paulo SP, 17.128",
            "Trapichão, Maceió, Alagoas AL, Gov. Estadual, Capacidade: 17.126",
            "Adail Nunes da Silva, Taquaritinga, São Paulo SP, Gov. Municipal, Capacidade: 16.805",
            "Anacleto Campanella, São Caetano do Sul, 16.744",
            "Martins Pereira, São José dos Campos, 16.500",
            "Arena Cruzeiro, Cachoeirinha, Rio Grande do Sul RS, Privado",
            "Silvio Salles, Catanduva, São Paulo SP, Gov. Municipal, Capacidade: 16.444",
            "Uberabão, Uberaba, Minas Gerais MG, 16.384",
            "Décio Vitta, Americana, São Paulo SP, 16.300",
            "Jóia da Princesa, Feira de Santana, Bahia BA, 16.274",
            "Curuzu, Belém, Pará PA, Privado,Capacidade: 16.200",
            "Herminio Ometto, Araras, São Paulo SP, 16.096",
            "Dario Rodrigues Leite, Guaratinguetá, Gov. Municipal, Capacidade: 16.095",
            "Carneirão, Alagoinhas, Bahia BA, 16.000",
            "Pedro Eymard, Morada Nova, Ceará CE",
            "Gilbertão, Lins, São Paulo SP, 15.770",
            "Primeiro de Maio, São Bernardo do Campo, 15.759",
            "Prefeito José Costa, Espírito Santo do Pinhal, 15.727",
            "Arena Batistão, Aracaju, Sergipe SE, Gov. Estadual, Capacidade: 15.586",
            "Boca do Lobo, Pelotas, Rio Grande do Sul RS, Privado,Capacidade: 15.478",
            "Melão, Varginha, Minas Gerais MG, Gov. Municipal, Capacidade: 15.471",
            "Sócrates Stamato, Bebedouro, São Paulo SP, 15.300",
            "Jayme Cintra, Jundiaí, Privado,Capacidade: 15.155",
            "Frasqueirão, Natal, Rio Grande do Norte RN, 15.082",
            "Bento de Abreu, Marília, São Paulo SP, Gov. Municipal, Capacidade: 15.010",
            "Alfredo Chiavegato, Jaguariúna, 15.000",
            "Arapucão, Jataí, Goiás GO",
            "Carlos Affini, Paraguaçu Paulista, São Paulo SP",
            "Montanha dos Vinhedos, Bento Gonçalves, Rio Grande do Sul RS, Privado",
            "JK, Itumbiara, Goiás GO, Gov. Municipal",
            "José Maria Campos Maia, Mirassol, São Paulo SP",
            "Moacyrzão, Macaé, Rio de Janeiro RJ, Privado",
            "Giulite Coutinho, Mesquita",
            "Maria Teresa Breda, Olímpia, São Paulo SP, Gov. Municipal",
            "Vermelhão da Serra, Passo Fundo, Rio Grande do Sul RS, Privado",
            "Torquato Pontes, Rio Grande",
            "Arthur Marinho, Corumbá, Mato Grosso do Sul MS",
            "Antonio Lins Ribeiro Guimarães, Santa Bárbara d'Oeste, São Paulo SP, 14.913",
            "Lancha Filho, Franca, Gov. Municipal, Capacidade: 14.686",
            "Francisco Nogueira Filho, Mogi das Cruzes, 14.384",
            "Bruno José Daniel, Santo André, 14.185",
            "Anísio Haddad, São José do Rio Preto, Privado,Capacidade: 14.126",
            "Jorge Ismael de Biasi, Novo Horizonte, 12.872",
            "Amaros, Itápolis, 14.074",
            "Francisco Novelletto Neto, Porto Alegre, Rio Grande do Sul RS, 14.000",
            "Serrinha, Goiânia, Goiás GO",
            "Walter Ribeiro, Sorocaba, São Paulo SP, Gov. Municipal, Capacidade: 13.772",
            "Zerão, Macapá, Amapá AP, Gov. Estadual, Capacidade: 13.680",
            "Olímpico, Goiânia, Goiás GO, 13.500",
            "Ícaro de Castro Melo, São Paulo, São Paulo SP, 13.400",
            "Otacília Patrício Arroyo, Monte Azul Paulista, Privado,Capacidade: 13.100",
            "Fortaleza, Barretos, Gov. Municipal, Capacidade: 13.007",
            "Gigante do Norte, Sinop, Mato Grosso MT, 13.000",
            "Bento Freitas, Pelotas, Rio Grande do Sul RS, Privado",
            "Oswaldo Scatena, Batatais, São Paulo SP",
            "Zezinho Magalhães, Jaú, 12.978",
            "Joaquim de Morais Filho, Taubaté, 12.896",
            "14 de Dezembro, Toledo, Paraná PR, Gov. Municipal, Capacidade: 12.500",
            "Fumeirão, Arapiraca, Alagoas AL",
            "Antônio Accioly, Goiânia, Goiás GO, Privado",
            "José Liberatti, Osasco, São Paulo SP, Gov. Municipal, Capacidade: 12.430",
            "Serra do Lago, Luziânia, Goiás GO, 12.300",
            "Cornélio de Barros, Salgueiro, Pernambuco PE, 12.070",
            "Ademir Cunha, Paulista, 12.000",
            "Caio Martins, Niterói, Rio de Janeiro RJ, Privado",
            "Marizão, Caicó, Rio Grande do Norte RN, Gov. Estadual",
            "Municipal de Quiterianópolis, Quiterianópolis, Ceará CE, Gov. Municipal",
            "Baenão, Belém, Pará PA, Privado",
            "Colosso do Tapajós, Santarém, Gov. Municipal",
            "Alonso Carvalho Braga, Tupã, São Paulo SP",
            "Antônio Pena, Catu, Bahia BA",
            "Perpetão, Cajazeiras, Paraíba PB, Gov. Estadual",
            "OBA, Goiânia, Goiás GO, Privado,Capacidade: 11.788",
            "Breno Ribeiro do Val, Osvaldo Cruz, São Paulo SP, Gov. Municipal, Capacidade: 11.784",
            "Luiz Viana Filho, Itabuna, Bahia BA, 11.745",
            "Mirandão, Crato, Ceará CE, 11.732",
            "Lomantão, Vitória da Conquista, Bahia BA, 11.538",
            "José Cavalcanti, Patos, Paraíba PB, 11.500",
            "Nhozinho Santos, São Luís, Maranhão MA, 11.429",
            "Adhermazão, Araçatuba, São Paulo SP, 11.274",
            "Geraldão, Tauá, Ceará CE, 11.168",
            "Gigante do Itiberê, Paranaguá, Paraná PR, 11.000",
            "CE Umuarama, Umuarama",
            "Marizão, Sousa, Paraíba PB",
            "Carneirão, Vitória de Santo Antão, Pernambuco PE, 10.911",
            "Jonas Duarte, Anápolis, Goiás GO, 10.707",
            "Grito da República, Olinda, Pernambuco PE, 10.700",
            "Bom Jesus da Lapa, Apucarana, Paraná PR, 10.682",
            "Germano Krüger, Ponta Grossa, Privado,Capacidade: 10.632",
            "Junco, Sobral, Ceará CE, Gov. Municipal, Capacidade: 10.500",
            "Trabalhador, Resende, Rio de Janeiro RJ",
            "Colina, Manaus, Amazonas AM, Gov. Estadual, Capacidade: 10.451",
            "Dos Pássaros, Arapongas, Paraná PR, 10.440",
            "Domingão, Horizonte, Ceará CE, Gov. Municipal, Capacidade: 10.400",
            "Pedro Alves do Nascimento, Patrocínio, Minas Gerais MG, 10.250",
            "Vavazão, Maruim, Sergipe SE, Gov. Estadual, Capacidade: 10.235",
            "Parque do Bacurau, Cametá, Pará PA, Gov. Municipal, Capacidade: 10.230",
            "Nicolau Alayon, São Paulo, São Paulo SP, Privado,Capacidade: 10.117",
            "Barrettão, Ceará-Mirim, Rio Grande do Norte RN, Gov. Municipal, Capacidade: 10.068",
            "José Sidney Cunha, Capão Bonito, São Paulo SP, Privado,Capacidade: 10.022",
            "Octávio da Silva Bastos, São João da Boa Vista, Gov. Municipal, Capacidade: 10.002",
            "Arena do Calçado, Nova Serrana, Minas Gerais MG, 10.000",
            "Bernardo Rubinger de Queiroz, Patos de Minas",
            "Teotônio Vilela, Viçosa, Alagoas AL",
            "Florestão, Rio Branco, Acre AC",
            "Estrela D'Alva, Bagé, Rio Grande do Sul RS, Privado",
            "Cristo Rei, São Leopoldo",
            "Complexo Esportivo da ULBRA, Canoas",
            "Vila Olímpica, Curitiba, Paraná PR",
            "VGD, Londrina",
            "Nogueirão, Mossoró, Rio Grande do Norte RN",
            "Luís Augusto de Oliveira, São Carlos, São Paulo SP, Gov. Municipal",
            "Distrital do Inamar, Diadema",
            "Aryzão, Campos dos Goytacazes, Rio de Janeiro RJ, Privado",
            "Jair Siqueira Bittencourt, Itaperuna",
            "Arena Guanabara, Araruama",
            "Odair Gama, Três Rios",
            "Aluizão, Porto Velho, Rondônia RO, Gov. Municipal",
            "Canarinho, Boa Vista, Roraima RR, Gov. Estadual",
            "Augustinho Lima, Sobradinho, Distrito Federal (Brasil) DF, Gov. Distrital",
            "Frei Epifânio, Imperatriz, Maranhão MA, Gov. Municipal",
            "Presidente Médici, Itabaiana, Sergipe SE, Gov. Estadual",
            "Nilton Santos, Palmas, Tocantins TO",
            "Ribeirão, Tocantinópolis, Privado",
            "Passo das Emas, Lucas do Rio Verde, Mato Grosso MT, Gov. Municipal",
            "Arena Verde, Paragominas, Pará PA",
            "Rosenão, Parauapebas, Pará PA",
            "Arena do Juruá, Cruzeiro do Sul, Acre AC"
        ]
    }
}

module.exports = SportsHelpers;